#!/bin/bash

Url="http://dictionary.reference.com/browse/"

function usage() {
	echo "Usage: $(basename $0) <word>"
}

if [ $# -lt 1 ]; then
	usage
	exit 1
fi

Word=$1
curl -s $Url$Word | \
xmllint --html --xpath 'string(//source[@type="audio/mpeg"]/@src)' - 2>/dev/null
echo
