---
- name: Copy bashrc config
  template: src=01-bashrc-elixir.j2
            dest=/home/{{user}}/.bashrc.d/01-bashrc-elixir

- name: Install kiex 1/2
  get_url: url=https://raw.githubusercontent.com/taylor/kiex/master/kiex
           dest=/home/{{user}}/bin/
           mode=0755
  register: kiex

- name: Install kiex 2/2
  command: kiex setup
  when: kiex is changed

- name: List know versions
  command: kiex list known

- name: Install versions
  command: kiex install {{item}} creates=/home/{{user}}/.kiex/elixirs/elixir-{{item}}.env
  with_items:
  - '1.9.1'
