---
- name: Install asdf plugin
  command: asdf plugin-add elixir https://github.com/asdf-vm/asdf-elixir.git
  register: result
  failed_when:
  - result.rc != 0
  - "'Plugin named elixir already added' not in result.stderr"

- name: Install asdf plugin
  command: asdf plugin-add elixir https://github.com/asdf-vm/asdf-elixir.git
  register: result
  failed_when:
  - result.rc != 0
  - "'Plugin named elixir already added' not in result.stderr"

- name: Fix in
  command: sed --in-place 's/make clean test/make compile/' /home/{{user}}/.asdf/plugins/elixir/bin/install

- name: Build versions
  command: asdf install elixir ref:v{{item}} creates=/home/{{user}}/.asdf/installs/elixir/ref-v{{item}}
  with_items:
  - '{{elixir_ver}}'

- name: Fix out
  command: sed --in-place 's/make compile/make clean test/' /home/{{user}}/.asdf/plugins/elixir/bin/install

- name: Install
  command: asdf global elixir ref:v{{elixir_ver}}
