---
- name: Install 1/2
  become: true
  community.general.snap:
    name: minizinc
    classic: true

- name: Install 2/2
  copy: src={{item}}
        dest=/home/{{user}}/.local/share/applications/{{item}}
  with_items:
  - minizinc-ide.desktop
