---
- name: Copy bashrc config
  copy: src=01-bashrc-rust
        dest=/home/{{user}}/.bashrc.d/

# https://doc.rust-lang.org/cargo/reference/config.html
- name: Copy cargo config
  copy: src=config
        dest=/home/{{user}}/.cargo/

# https://www.rust-lang.org/tools/install
- name: Install Rustup
  shell: curl -sSf https://sh.rustup.rs | sh -s -- -q -y --no-modify-path creates=/home/{{user}}/.cargo/bin/rustup

# https://hoverbear.org/blog/setting-up-a-rust-devenv/
- name: Install components
  shell: rustup component add {{item}}
  with_items:
  - clippy
  - rustfmt
  - rust-docs
  - rust-src

- name: Install Rustup stuff
  shell: rustup install {{item}}
  with_items:
  - nightly

- name: Update Rustup
  shell: rustup update

- name: Install Cargo stuff
  shell: cargo install {{item}}
  with_items:
  - cargo-expand # https://github.com/dtolnay/cargo-expand
