#!/usr/bin/env bash

if [[ $# -ne 1 ]] && [[ $# -ne 2 ]]; then
    echo "usage: $(basename $0) <REMOTE_DIR> [LOCAL_DIR]"
    echo "example:"
    echo "  \$ $(basename $0) storage/downloads"
    exit 1
fi

REMOTE_DIR=${1}
REMOTE_REAL_DIR=$(ssh phone "realpath ${REMOTE_DIR}")
LOCAL_DIR=${2:-$(mktemp -d)}

if [[ ${DEBUG} == "1" ]]; then
    echo "REMOTE_DIR     : ${REMOTE_DIR}"
    echo "REMOTE_REAL_DIR: ${REMOTE_REAL_DIR}"
    echo "LOCAL_DIR      : ${LOCAL_DIR}"
    DEVICE=/dev/stderr
else
    DEVICE=/dev/null
fi

echo "sshfs phone:${REMOTE_REAL_DIR} ${LOCAL_DIR}" | tee ${DEVICE} | bash
if [[ $? -ne 0 ]]; then
    rm -f ${TMP}
    exit 3
fi
rm -f ${TMP}

LOCAL_ABS_DIR=$(realpath ${LOCAL_DIR})
echo "Remote '${REMOTE_REAL_DIR}' is mounted to '${LOCAL_ABS_DIR}'"
echo "To exit and unmount, run: $ exit"
echo "To manually unmount, run: $ fusermount -u ${LOCAL_ABS_DIR}"

pushd ${LOCAL_DIR} > /dev/null; bash -i; popd > /dev/null
fusermount -u ${LOCAL_ABS_DIR}
