---
#
# https://www.mongodb.com/docs/manual/tutorial/install-mongodb-on-ubuntu/
#

- name: Add apt key
  become: true
  apt_key:
    url: https://www.mongodb.org/static/pgp/server-7.0.asc
    state: present

- name: Add apt repo
  become: true
  apt_repository:
    repo: 'deb https://repo.mongodb.org/apt/ubuntu {{ubuntu_codename}}/mongodb-org/7.0 multiverse'
    state: present

- name: Install
  become: true
  apt:
    name:
    - mongodb-org # Metapackage
    state: latest

- name: Start
  become: true
  service:
    name: mongod
    enabled: true
    state: started
