---
- name: Set vars
  set_fact:
    compass_ver: 1.43.2

#
# https://www.mongodb.com/docs/manual/tutorial/install-mongodb-on-ubuntu/
#

- name: Add apt key
  become: true
  apt_key:
    url: https://www.mongodb.org/static/pgp/server-7.0.asc
    state: present

- name: Add apt repo
  become: true
  apt_repository:
    repo: 'deb https://repo.mongodb.org/apt/ubuntu {{ubuntu_codename}}/mongodb-org/7.0 multiverse'
    state: present

- name: Install
  become: true
  apt:
    name:
    - mongodb-org # Metapackage
    state: latest

- name: Start
  become: true
  service:
    name: mongod
    enabled: true
    state: started

#
# https://www.mongodb.com/try/download/compass
#

- name: Download Compass Deb
  get_url:
    url: https://downloads.mongodb.com/compass/mongodb-compass_{{compass_ver}}_amd64.deb
    dest: "{{cache_dir}}/mongodb-compass_{{compass_ver}}_amd64.deb"

- name: Install Compass Deb
  become: true
  apt:
    deb: "{{cache_dir}}/mongodb-compass_{{compass_ver}}_amd64.deb"
