#!/bin/bash

if [[ $# != 3 ]]; then
    echo "Usage: `basename $0` <COMMAND> <ARG1> <ARG2>"
    echo "Will run: <COMMAND> <ARG2> <ARG1>"
    exit 1
fi

command=${1}
first=${2}
second=${3}

${command} ${second} ${first}
