#!/bin/bash

# https://github.com/envygeeks/jekyll-docker

# usage:
# $ jekyll --help
# $ jekyll new <name>
# $ jekyll build
# $ jekyll serve

export JEKYLL_VERSION=3.8
docker run --rm --publish=4000:4000 --volume="$PWD:/srv/jekyll" -it jekyll/jekyll:$JEKYLL_VERSION jekyll "$@"
