#!/bin/bash

if [[ $# -ne 1 ]] && [[ $# -ne 2 ]] && [[ $# -ne 3 ]]; then
    echo "[R]emote [ERL]ang node helper"
    echo "Usage: $(basename $0) <NAME@HOST> [<ping> | remsh | entop | cookie | call <CALL>]"
    echo "Where:"
    echo "  ping   - Start local node and ping remote node (default)"
    echo "  remsh  - Connect to remote node"
    echo "  entop  - Connect entop to remote node"
    echo "  cookie - Print remote node's cookie"
    echo "  call   - Make RPC call. CALL must be \"Module, Function, Args\""
    exit 1
fi

node=$1
cmd=${2-ping}

host=$(echo $node | awk -F@ '{print $2}')
case $host in
10.249.*)
    echo Connecting to Prod...
    name="-name adm$$@127.0.0.1"
    cookie=$(ssh $host 'cat .erlang.cookie')
    ;;
10.252.*)
    echo Connecting to Sandbox...
    name="-name adm$$@127.0.0.1"
    cookie=$(ssh $host 'sudo cat /home/*/.erlang.cookie')
    ;;
$(hostname))
    name="-sname adm$$"
    cookie=$(cat ~/.erlang.cookie)
    ;;
*)
    echo "Unknown host: $host"
    exit 1
esac

case $cmd in
cookie)
    echo $cookie
    ;;
ping)
    echo "Exit with double Ctrl-C"
    erl $name -setcookie $cookie -eval "net_adm:ping('$node')."
    ;;
remsh)
    echo "Exit with double Ctrl-C"
    erl $name -hidden -setcookie $cookie -remsh $node
    ;;
entop)
    entop $node $name -setcookie $cookie
    ;;
call)
   code=${3-"erlang,node,[]"}
   erl $name -hidden -noshell -setcookie $cookie -eval "io:format(\"~p~n\", [rpc:call('$node', $code)]), init:stop()."
   ;;
*)
    echo "Unknown command: $cmd"
    exit 1
esac
