#!/bin/bash -e

if [[ $# -ne 1 ]] && [[ $# -ne 2 ]] && [[ $# -ne 3 ]]; then
    echo "[R]emote [ERL]ang node helper"
    echo "Usage: $(basename $0) <NAME@HOST> [<ping> | remsh | entop | cookie | call <MFA> | load <BEAM>]"
    echo "Where:"
    echo "  ping   - Start the local node and ping the remote node (default)"
    echo "  remsh  - Connect to the remote node"
    echo "  entop  - Connect entop to the remote node"
    echo "  cookie - Print remote node's cookie"
    echo "  call   - Make a RPC call. MFA must be \"Module, Function, [Args]\""
    echo "  load   - Load BEAM to the remote node"
    exit 1
fi

node=$1
cmd=${2-ping}

host=$(echo $node | awk -F@ '{print $2}')
case $host in
10.249.*)
    name="-name adm$$@127.0.0.1"
    cookie=$(ssh $host 'cat ~/.erlang.cookie')
    ;;
10.252.*)
    name="-name adm$$@127.0.0.1"
    cookie=$(ssh $host 'sudo cat /home/*/.erlang.cookie')
    ;;
127.0.0.1)
    name="-name adm$$@127.0.0.1"
    cookie=$(cat ~/.erlang.cookie)
    ;;
$(hostname))
    name="-sname adm$$"
    cookie=$(cat ~/.erlang.cookie)
    ;;
*)
    echo "Unknown host: $host"
    exit 1
esac

function rpc_call() {
    local node=$1
    local name=$2
    local cookie=$3
    local mfa=$4
    erl $name -hidden -noshell -setcookie $cookie -eval "io:format(\"~p~n\", [rpc:call('$node', $mfa)]), init:stop()."
}

case $cmd in
cookie)
    echo $cookie
    ;;
ping)
    echo "Exit with double Ctrl-C"
    erl $name -setcookie $cookie -eval "net_adm:ping('$node')."
    ;;
remsh)
    echo "Exit with double Ctrl-C"
    erl $name -hidden -setcookie $cookie -remsh $node
    ;;
entop)
    entop $node $name -setcookie $cookie
    ;;
call)
   mfa=${3-"erlang,node,[]"}
   rpc_call "$node" "$name" "$cookie" "$mfa"
   ;;
load)
   if [[ $3 ]]; then
       beam=${3}
       module=$(basename ${beam%.*})
       path=$(rpc_call "$node" "$name" "$cookie" "code,which,['$module']")
       case $host in
       10.249.*)
           ssh $host "tee $path >/dev/null" <$beam || exit 1
       ;;
       10.252.*)
           ssh $host "sudo tee $path >/dev/null" <$beam || exit 1
       ;;
       127.0.0.1)
           tee $path >/dev/null <$beam
       ;;
       $(hostname))
           tee $path >/dev/null <$beam
       ;;
       esac
       rpc_call "$node" "$name" "$cookie" "c,l,['$module']"
   else
       echo "BEAM param expected"
       exit 1
   fi
   ;;
*)
    echo "Unknown command: $cmd"
    exit 1
esac
