#!/bin/bash

if [[ $# -ne 1 ]] && [[ $# -ne 2 ]]; then
    echo "[R]emote [ERL]ang node helper"
    echo "Usage: $(basename $0) <NAME@IP> [<ping> | remsh | entop | cookie]"
    echo "Where:"
    echo "  ping   - Start local node and ping remote node (default)"
    echo "  remsh  - Connect to remote node"
    echo "  entop  - Connect entop to remote node"
    echo "  cookie - Print remote node's cookie"
    exit 1
fi

node=$1
cmd=${2-ping}

ip=$(echo $node | awk -F@ '{print $2}')
case $ip in
10.249.*)
    echo Connecting to Prod...
    cookie=$(ssh $ip 'cat .erlang.cookie')
    ;;
10.252.*)
    echo Connecting to Sandbox...
    cookie=$(ssh $ip 'sudo cat /home/*/.erlang.cookie')
    ;;
*)
    echo "Unknown host: $ip"
    exit 1
esac

case $cmd in
cookie)
    echo $cookie
    ;;
ping)
    echo "Exit with double Ctrl-C"
    erl -name adm$$@127.0.0.1 -setcookie $cookie -eval "net_adm:ping('$node')."
    ;;
remsh)
    echo "Exit with double Ctrl-C"
    erl -name adm$$@127.0.0.1 -setcookie $cookie -remsh $node
    ;;
entop)
    entop $node -name adm$$@127.0.0.1 -setcookie $cookie
    ;;
*)
    echo "Unknown command: $cmd"
    exit 1
esac
