#!/bin/bash -e

function usage() {
    echo "Usage: $(basename $0)"
}

function update() {
    ips=$(hosts.sh Dev v2.4 dmu)
    last_ip=$(echo $ips | tail -1)
    for ip in $ips; do
        ec2=$(ssh $ip 'curl -s http://169.254.169.254/latest/meta-data/instance-id')
        echo "Terminating $ip ($ec2)"
        aws ec2 terminate-instances --instance-ids $ec2
        [[ "$ip" != "$last_ip" ]] && sleep 600
    done
}

if [[ $# -ne 0 ]]; then
   usage
   exit 1
fi

echo "Do you really want to update Dev DMU nodes?"
PS3="> "
opts="Yes No"
select opt in $opts; do
   case $opt in
   Yes)
       update
       exit
       ;;
   No)
       exit
       ;;
   esac
done
