---
- hosts: localhost
  connection: local
  user: ten0s
  vars:
    user: ten0s
  tasks:
  - name: Update apt cache
    sudo: yes
    apt: update_cache=yes cache_valid_time=86400

  - name: Install apt-file
    sudo: yes
    apt: name=apt-file state=latest

  - name: Update apt-file cache
    sudo: yes
    shell: apt-file update

  - name: Install stuff
    sudo: yes
    apt: name={{item}} state=latest
    with_items:
    - autokey-gtk
    - curl
    - dropbox
    - emacs
    - htop
    - git
    - keepassx
    - mc
    - meld
    - vlc
    - wget

  - name: Remove stuff
    sudo: yes
    apt: name={{item}} state=absent
    with_items:
    - aptitude
    - cowsay
    - fortune

  - name: Symlink 'refs'
    file: >
      src=/home/{{user}}/Dropbox/refs
      dest=/home/{{user}}/refs
      state=link
      force=yes

  - name: Symlink global configs
    sudo: yes
    file: >
      src=/home/{{user}}/dotfiles/configs/global/{{item.name}}
      dest={{item.path}}/{{item.name}}
      state=link
      force=yes
    with_items:
    - {name: locale, path: /etc/default/}
    - {name: 40custom_load-xmodmap, path: /etc/X11/Xsession.d/}

  - name: Symlink local configs
    file: >
      src=/home/{{user}}/dotfiles/configs/local/{{item}}
      dest=/home/{{user}}/{{item}}
      state=link
      force=yes
    with_items:
    - .bashrc
    - .gitconfig
    - .Xmodmap
