---
- hosts: localhost
  connection: local
  user: ten0s
  vars:
    user: ten0s
    cache_dir: /var/cache/ansible
    vagrant_ver: 1.9.5
    vbox_ver: 5.0
    jq_ver: 1.5
    skype_ver: 8.11.0.4
    slack_ver: 3.0.2
    mvn_ver: 3.5.2
    realvnc_viewer_ver: 6.17.1113
  tasks:
  - {include: tasks/common.yml     , tags: ["common"]}
  - {include: tasks/carcharodon.yml, tags: ["carcharodon"], when: ansible_hostname == "carcharodon"}
  - {include: tasks/megalodon.yml  , tags: ["megalodon"]  , when: ansible_hostname == "megalodon"}
  - {include: tasks/orca.yml       , tags: ["orca"]       , when: ansible_hostname == "orca"}
  - {include: tasks/dev.yml        , tags: ["dev"]}
  - {include: tasks/java.yml       , tags: ["java"]}
  - {include: tasks/scala.yml      , tags: ["scala"]}
  - {include: tasks/erl.yml        , tags: ["erl"]}
  - {include: tasks/cpp.yml        , tags: ["cpp"]}
  - {include: tasks/py.yml         , tags: ["py"]}
  - {include: tasks/js.yml         , tags: ["js"]}
  - {include: tasks/hs.yml         , tags: ["hs"]}
  - {include: tasks/racket.yml     , tags: ["racket"]}
  - {include: tasks/vagrant.yml    , tags: ["vagrant"]}
  - {include: tasks/docker.yml     , tags: ["docker"]}
  - {include: tasks/oracle.yml     , tags: ["oracle"]}
  - {include: tasks/xymon.yml      , tags: ["xymon"]}
