---
- hosts: localhost
  connection: local
  user: ten0s
  vars:
    user: ten0s
  tasks:
  - {include: tasks/common.yml, tags: ["common"]}
  - {include: tasks/anki.yml, tags: ["anki"]}
  - {include: tasks/megalodon.yml, tags: ["megalodon"], when: '"{{ansible_hostname}}" == "megalodon"'}
  - {include: tasks/dev.yml projects_dir=~/projects/, tags: ["dev"]}
  - {include: tasks/erl.yml, tags: ["erl"]}
  - {include: tasks/cpp.yml, tags: ["cpp"]}
  - {include: tasks/py.yml, tags: ["py"]}
  - {include: tasks/sml.yml, tags: ["sml"]}
  - {include: tasks/ocaml.yml, tags: ["ocaml"]}
  - {include: tasks/virt.yml cache_dir=/var/cache/ansible/virt/ vagrant_ver=1.7.4 vbox_ver=4.3, tags: ["virt"]}
  - {include: tasks/wine.yml, tags: ["wine"]}
