---
- hosts: localhost
  gather_facts: no
  connection: local
  user: ten0s
  vars:
    user: ten0s
    cache_dir: /var/cache/ansible
    anki2_ver: 2.1.5-linux-amd64
    docker_compose_ver: 1.15.0
    jq_ver: 1.5
    mvn_ver: 3.5.4
    skype_ver: 8.18.0.6
    slack_ver: 3.0.2-amd64
    vagrant_ver: 2.2.3
    virtualbox_ver: 6.0
  tasks:
  - {import_role: name=common      , tags: ["common"]}

  - {import_role: name=algs4       , tags: ["algs4"]}
  - {import_role: name=anki2       , tags: ["anki2"]}
  - {import_role: name=autokey     , tags: ["autokey"]}
  - {import_role: name=awscli      , tags: ["awscli"]}
  - {import_role: name=chrome      , tags: ["chrome"]}
  - {import_role: name=cpp         , tags: ["cpp"]}
  - {import_role: name=docker      , tags: ["docker"]}
  - {import_role: name=dropbox     , tags: ["dropbox"]}
  - {import_role: name=emacs       , tags: ["emacs"]}
  - {import_role: name=erl         , tags: ["erl"]}
  - {import_role: name=git         , tags: ["git"]}
  - {import_role: name=java        , tags: ["java"]}
  - {import_role: name=jq          , tags: ["jq"]}
  - {import_role: name=js          , tags: ["js"]}
  - {import_role: name=meld        , tags: ["meld"]}
  - {import_role: name=py          , tags: ["py"]}
  - {import_role: name=skype       , tags: ["skype"]}
  - {import_role: name=vagrant     , tags: ["vagrant"]}
  - {import_role: name=virtualbox  , tags: ["virtualbox"]}

  - {import_role: name=carcharodon , tags: ["carcharodon"], when: ansible_hostname == "carcharodon"}
  - {import_role: name=megalodon   , tags: ["megalodon"]  , when: ansible_hostname == "megalodon"}
