---
- hosts: localhost
  gather_facts: no
  connection: local
  user: ten0s
  vars:
    user: ten0s
    cache_dir: /var/cache/ansible
  tasks:
  - {import_role: name=common      , tags: ["common"]}
  - {import_role: name=emacs       , tags: ["emacs"]}
  - {import_role: name=carcharodon , tags: ["carcharodon"], when: ansible_hostname == "carcharodon"}
  - {import_role: name=megalodon   , tags: ["megalodon"]  , when: ansible_hostname == "megalodon"}
  - {import_role: name=dev         , tags: ["dev"]}
  - {import_role: name=java        , tags: ["java"]}
  - {import_role: name=scala       , tags: ["scala"]}
  - {import_role: name=erl         , tags: ["erl"]}
  - {import_role: name=cpp         , tags: ["cpp"]}
  - {import_role: name=py          , tags: ["py"]}
  - {import_role: name=js          , tags: ["js"]}
  - {import_role: name=hs          , tags: ["hs"]}
  - {import_role: name=racket      , tags: ["racket"]}
  - {import_role: name=vagrant     , tags: ["vagrant"]}
  - {import_role: name=virtualbox  , tags: ["virtualbox"]}
  - {import_role: name=docker      , tags: ["docker"]}
  - {import_role: name=oracle      , tags: ["oracle"]}
  - {import_role: name=xymon       , tags: ["xymon"]}
  - {import_role: name=vscode      , tags: ["vscode"]}
  - {import_role: name=algs4       , tags: ["algs4"]}
  - {import_role: name=anki2       , tags: ["anki2"]}
