---
- hosts: localhost
  gather_facts: false
  connection: local
  user: ten0s
  vars:
    user: ten0s
    cache_dir: /var/cache/ansible
    erl_ver: 21.3.8.17
    cpp_std: c++17
    ubuntu_codename: jammy # cat /etc/os-release
  tasks:
  - {import_role: name=common        , tags: ["common"]}

  - {import_role: name=algs4         , tags: ["algs4"]}
  - {import_role: name=anki2         , tags: ["anki2"]}
  - {import_role: name=antlr         , tags: ["antlr"]}
  - {import_role: name=anyconnect    , tags: ["anyconnect"]}
  - {import_role: name=asdf          , tags: ["asdf"]}
  - {import_role: name=autokey       , tags: ["autokey"]}
  - {import_role: name=awscli2       , tags: ["awscli2"]}
  - {import_role: name=bastyon       , tags: ["bastyon"]}
  - {import_role: name=chrome        , tags: ["chrome"]}
  - {import_role: name=cpp           , tags: ["cpp"]}
  - {import_role: name=cron          , tags: ["cron"]}
  - {import_role: name=debug         , tags: ["debug"]}
  - {import_role: name=docker        , tags: ["docker"]}
  - {import_role: name=dropbox       , tags: ["dropbox"]}
  - {import_role: name=elixir        , tags: ["elixir"]}
  - {import_role: name=emacs         , tags: ["emacs"]}
  - {import_role: name=erl           , tags: ["erl"]}
  - {import_role: name=exercism      , tags: ["exercism"]}
  - {import_role: name=git           , tags: ["git"]}
  - {import_role: name=googledrive   , tags: ["googledrive"]}
  - {import_role: name=help          , tags: ["help"]}
  - {import_role: name=java          , tags: ["java"]}
  - {import_role: name=jq            , tags: ["jq"]}
  - {import_role: name=jupyter       , tags: ["jupyter"]}
  - {import_role: name=latex         , tags: ["latex"]}
  - {import_role: name=meld          , tags: ["meld"]}
  - {import_role: name=mfakeys       , tags: ["mfakeys"]}
  - {import_role: name=mimeapps      , tags: ["mimeapps"]}
  - {import_role: name=minizinc      , tags: ["minizinc"]}
  - {import_role: name=mysql         , tags: ["mysql"]}
  - {import_role: name=nodejs        , tags: ["nodejs"]}
  - {import_role: name=openscad      , tags: ["openscad"]}
  - {import_role: name=openssl       , tags: ["openssl"]}
  - {import_role: name=oracle        , tags: ["oracle"]}
  - {import_role: name=osquery       , tags: ["osquery"]}
  - {import_role: name=phone         , tags: ["phone"]}
  - {import_role: name=postgresql    , tags: ["postgresql"]}
  - {import_role: name=prolog        , tags: ["prolog"]}
  - {import_role: name=py3           , tags: ["py3"]}
  - {import_role: name=racket        , tags: ["racket"]}
  - {import_role: name=rclone        , tags: ["rclone"]}
  - {import_role: name=rds           , tags: ["rds"]}
  - {import_role: name=rerl          , tags: ["rerl"]}
  - {import_role: name=rust          , tags: ["rust"]}
  - {import_role: name=scala         , tags: ["scala"]}
  - {import_role: name=shellcheck    , tags: ["shellcheck"]}
  - {import_role: name=skype         , tags: ["skype"]}
  - {import_role: name=slack         , tags: ["slack"]}
  - {import_role: name=snap          , tags: ["snap"]}
  - {import_role: name=teams         , tags: ["teams"]}
  - {import_role: name=teamviewer    , tags: ["teamviewer"]}
  - {import_role: name=telegram      , tags: ["telegram"]}
  - {import_role: name=tiddlydesktop , tags: ["tiddlydesktop"]}
  - {import_role: name=vagrant       , tags: ["vagrant"]}
  - {import_role: name=virtualbox    , tags: ["virtualbox"]}
  - {import_role: name=wine          , tags: ["wine"]}
  - {import_role: name=work          , tags: ["work"]}
  - {import_role: name=vscode        , tags: ["vscode"]}
  - {import_role: name=xymon         , tags: ["xymon"]}
  - {import_role: name=zoom          , tags: ["zoom"]}

  - {import_role: name=carcharodon   , tags: ["carcharodon"], when: ansible_hostname == "carcharodon"}
  - {import_role: name=megalodon     , tags: ["megalodon"]  , when: ansible_hostname == "megalodon"}
