---
- hosts: localhost
  connection: local
  user: ten0s
  vars:
    user: ten0s
    cache_dir: /var/cache/ansible
    clang_ver: 6.0
    anki2_ver: 2.1.5-linux-amd64
    asdf_ver: 0.7.3
    docker_compose_ver: 1.25.3 # https://github.com/docker/compose/releases
    elixir_ver: 1.9.1
    erl_ver: 19.3
    exercism_ver: 3.0.11
    jq_ver: 1.6
    mvn_ver: 3.6.0
    skype_ver: 8.54.0.91
    slack_ver: 4.1.2-amd64
    vagrant_ver: 2.2.7
    virtualbox_ver: 6.0
    ubuntu_codename: bionic # lsb_release -c OR cat /etc/os-release OR cat /etc/upstream-release/lsb-release
  tasks:
  - {import_role: name=common      , tags: ["common"]}

  - {import_role: name=algs4       , tags: ["algs4"]}
  - {import_role: name=anki2       , tags: ["anki2"]}
  - {import_role: name=anyconnect  , tags: ["anyconnect"]}
  - {import_role: name=asdf        , tags: ["asdf"]}
  - {import_role: name=autokey     , tags: ["autokey"]}
  - {import_role: name=awscli      , tags: ["awscli"]}
  - {import_role: name=chrome      , tags: ["chrome"]}
  - {import_role: name=cpp         , tags: ["cpp"]}
  - {import_role: name=docker      , tags: ["docker"]}
  - {import_role: name=dropbox     , tags: ["dropbox"]}
  - {import_role: name=elixir      , tags: ["elixir"]}
  - {import_role: name=emacs       , tags: ["emacs"]}
  - {import_role: name=erl         , tags: ["erl"]}
  - {import_role: name=exercism    , tags: ["exercism"]}
  - {import_role: name=git         , tags: ["git"]}
  - {import_role: name=java        , tags: ["java"]}
  - {import_role: name=jq          , tags: ["jq"]}
  - {import_role: name=js          , tags: ["js"]}
  - {import_role: name=meld        , tags: ["meld"]}
  - {import_role: name=mfakeys     , tags: ["mfakeys"]}
  - {import_role: name=mysql       , tags: ["mysql"]}
  - {import_role: name=openssl     , tags: ["openssl"]}
  - {import_role: name=oracle      , tags: ["oracle"]}
  - {import_role: name=postgresql  , tags: ["postgresql"]}
  - {import_role: name=py          , tags: ["py"]}
  - {import_role: name=scala       , tags: ["scala"]}
  - {import_role: name=shellcheck  , tags: ["shellcheck"]}
  - {import_role: name=skype       , tags: ["skype"]}
  - {import_role: name=slack       , tags: ["slack"]}
  - {import_role: name=teams       , tags: ["teams"]}
  - {import_role: name=vagrant     , tags: ["vagrant"]}
  - {import_role: name=virtualbox  , tags: ["virtualbox"]}
  - {import_role: name=work        , tags: ["work"]}
  - {import_role: name=xymon       , tags: ["xymon"]}

  - {import_role: name=carcharodon , tags: ["carcharodon"], when: ansible_hostname == "carcharodon"}
  - {import_role: name=megalodon   , tags: ["megalodon"]  , when: ansible_hostname == "megalodon"}
