---
- hosts: localhost
  connection: local
  user: ten0s
  vars:
    user: ten0s
  tasks:
  - include: tasks/common.yml
  - include: tasks/megalodon.yml
    when: '"{{ansible_hostname}}" == "megalodon"'
  - include: tasks/dev.yml projects_dir=~/projects/
  - include: tasks/erl.yml
  - include: tasks/python.yml
  - include: tasks/sml.yml
  - include: tasks/virt.yml cache_dir=/var/cache/ansible/virt/ vagrant_ver=1.7.2 vbox_ver=4.3
