---
- hosts: localhost
  connection: local
  user: ten0s
  vars:
    user: ten0s
    cache_dir: /var/cache/ansible/
    vagrant_ver: 1.7.4
    vbox_ver: 4.3
  tasks:
  - {include: tasks/common.yml   , tags: ["common"]}
  - {include: tasks/megalodon.yml, tags: ["megalodon"], when: '"{{ansible_hostname}}" == "megalodon"'}
  - {include: tasks/orca.yml     , tags: ["orca"]     , when: '"{{ansible_hostname}}" == "orca"'}
  - {include: tasks/dev.yml      , tags: ["dev"]}
  - {include: tasks/erl.yml      , tags: ["erl"]}
  - {include: tasks/cpp.yml      , tags: ["cpp"]}
  - {include: tasks/py.yml       , tags: ["py"]}
  - {include: tasks/sml.yml      , tags: ["sml"]}
  - {include: tasks/ocaml.yml    , tags: ["ocaml"]}
  - {include: tasks/vagrant.yml  , tags: ["vagrant"]}
  - {include: tasks/docker.yml   , tags: ["docker"]}
