---
- hosts: localhost
  connection: local
  tasks:
  - name: Update apt cache
    sudo: yes
    apt: update_cache=yes cache_valid_time=86400

  - name: Install SML deps
    sudo: yes
    apt: name={{item}} state=latest
    with_items:
    - libsmlnj-smlnj
    - mlton-compiler
    - smlnj
    - sml-mode

#https://github.com/dellsystem/smlunit
#http://www.cs.cornell.edu/~clarkson/courses/csci4223/2013sp/install-sml-emacs.php
#http://www.cs.cmu.edu/afs/cs/local/sml/common/smlguide/smlnj.htm
#http://sml-family.org/Basis/index.html
