---
- hosts: localhost
  connection: local
  tasks:
  - name: Update apt cache
    sudo: yes
    apt: update_cache=yes cache_valid_time=86400

  - name: Install SML deps
    sudo: yes
    apt: name={{item}} state=latest
    with_items:
    - libsmlnj-smlnj
    - mlton-compiler
    - rlwrap
    - smlnj
    - sml-mode
