---
- hosts: localhost
  connection: local
  sudo: yes
  vars:
    cache_dir: /tmp/ansible/virt
  tasks:
  - name: Create download cache dir
    file: >
      path={{cache_dir}}
      state=directory

  - name: Download Vagrant package
    get_url: >
      url=https://dl.bintray.com/mitchellh/vagrant/vagrant_1.7.1_x86_64.deb
      dest={{cache_dir}}/vagrant-1.7.1.deb

  - name: Install Vagrant
    apt: >
      deb={{cache_dir}}/vagrant-1.7.1.deb
      state=present

  - name: Download Virtualbox package
    get_url: >
       url=http://download.virtualbox.org/virtualbox/4.3.20/virtualbox-4.3_4.3.20-96996~Ubuntu~raring_amd64.deb
       dest={{cache_dir}}/virtualbox-4.3.20.deb

  - name: Install Virtualbox
    apt: >
      deb={{cache_dir}}/virtualbox-4.3.20.deb
      state=present
