---
- name: Install
  become: true
  apt: name={{item}} state=latest
  with_items:
  - libsmlnj-smlnj
  - mlton-compiler
  - rlwrap
  - smlnj
  - sml-mode

- name: Copy bashrc config
  copy: src=01-bashrc-sml
        dest=/home/{{user}}/.bashrc.d/
        backup=true
