---
- name: Set vars
  set_fact:
    # $ curl -s --head https://telegram.org/dl/desktop/linux | grep location
    telegram_ver: 4.9.7

- name: Download
  get_url:
    url: https://updates.tdesktop.com/tlinux/tsetup.{{telegram_ver}}.tar.xz
    dest: "{{cache_dir}}/tsetup.{{telegram_ver}}.tar.xz"

- name: Unarchive
  become: true
  unarchive:
    src: "{{cache_dir}}/tsetup.{{telegram_ver}}.tar.xz"
    dest: /opt/

- name: Install
  copy:
    src: "{{item}}"
    dest: "/home/{{user}}/.local/share/applications/{{item}}"
  with_items:
  - telegramdesktop.desktop
