---
# https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2-linux.html
- name: Download
  get_url:
    url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
    dest: "{{cache_dir}}/awscliv2.zip"
    force: true

- name: Unzip
  unarchive:
    src: "{{cache_dir}}/awscliv2.zip"
    dest: "/home/{{user}}/tmp/"

- name: Install
  become: true
  command: /home/{{user}}/tmp/aws/install --update

- name: Cleanup
  file:
    path: "/home/{{user}}/tmp/aws"
    state: absent

- name: Copy bashrc config
  copy:
    src: 01-bashrc-awscli
    dest: "/home/{{user}}/.bashrc.d/"

- name: Configure SSO
  debug: msg='https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-sso.html'
