---
- name: Symlink $HOME/anki2
  file: src=/home/{{user}}/Dropbox/refs/anki2
        dest=/home/{{user}}/anki2
        state=link
        force=true

- name: MIME associations 1/3
  copy: src=files/configs/local/{{item}}
        dest=/home/{{user}}/.local/share/applications/{{item}}
        backup=true
  with_items:
  - evincex.desktop

- name: MIME associations 2/3
  copy: src=files/scripts/{{item}}
        dest=/home/{{user}}/bin/{{item}}
        backup=true
  with_items:
  - evincex.sh

- name: MIME associations 3/3
  lineinfile:
    path: /home/{{user}}/.local/share/applications/mimeapps.list
    backup: true
    regexp: "x-scheme-handler/evincex=evincex.desktop"
    insertafter: "^[Added Associations]"
    line: "x-scheme-handler/evincex=evincex.desktop;"
    state: present

- name: Install Anki2 deps
  become: true
  apt: name={{item}}
       state=present
  with_items:
  - dvipng
  - texlive-latex-base

- name: Install Anki2 1/3
  get_url: url=https://apps.ankiweb.net/downloads/current/anki-{{anki2_ver}}-linux-amd64.tar.bz2
           dest={{cache_dir}}/anki-{{anki2_ver}}-linux-amd64.tar.bz2

- name: Install Anki2 2/3
  unarchive: src={{cache_dir}}/anki-{{anki2_ver}}-linux-amd64.tar.bz2
             dest=/home/{{user}}/tmp/

- name: Install Anki2 3/3
  become: true
  command: make install chdir=/home/{{user}}/tmp/anki-{{anki2_ver}}-linux-amd64/

# Add-ons used:
# https://ankiweb.net/shared/info/2055492159
# https://ankiweb.net/shared/info/208879074
