---
- set_fact:
    launchers:
    - evincex
    - manx

- name: Symlink $HOME/anki2
  file: src=/home/{{user}}/Dropbox/refs/anki2
        dest=/home/{{user}}/anki2
        state=link
        force=true

- name: MIME associations 1/3
  copy: src=files/configs/local/{{item}}.desktop
        dest=/home/{{user}}/.local/share/applications/{{item}}.desktop
        backup=true
  with_items:
  - "{{launchers}}"

- name: MIME associations 2/3
  copy: src=files/scripts/{{item}}.sh
        dest=/home/{{user}}/bin/{{item}}.sh
        mode=0755
        backup=true
  with_items:
  - "{{launchers}}"

- name: MIME associations 3/3
  lineinfile:
    path: /home/{{user}}/.local/share/applications/mimeapps.list
    backup: true
    regexp: "x-scheme-handler/{{item}}={{item}}.desktop"
    insertafter: "^[Added Associations]"
    line: "x-scheme-handler/{{item}}={{item}}.desktop;"
    state: present
  with_items:
  - "{{launchers}}"

- name: Install Anki2 deps
  become: true
  apt: name={{item}}
       state=present
  with_items:
  - dvipng
  - texlive-latex-base

- name: Install Anki2 1/5
  get_url: url=https://apps.ankiweb.net/downloads/current/anki-{{anki2_ver}}.tar.bz2
           dest={{cache_dir}}/anki-{{anki2_ver}}.tar.bz2

- name: Install Anki2 2/5
  unarchive: src={{cache_dir}}/anki-{{anki2_ver}}.tar.bz2
             dest=/home/{{user}}/tmp/
             creates=/home/{{user}}/tmp/anki-{{anki2_ver}}
  register: anki

- name: Install Anki2 3/5
  become: true
  command: make install chdir=/home/{{user}}/tmp/anki-{{anki2_ver}}/
  when: anki.changed

- name: Install Anki2 4/5
  copy: src=files/scripts/{{item}}
        dest=/home/{{user}}/bin/{{item}}
        mode=0755
        backup=true
  with_items:
  - anki-dropbox-sync.sh

- name: Install Anki2 5/5
  become: true
  copy: src=files/configs/global/{{item}}
        dest=/usr/local/share/applications/{{item}}
        backup=true
  with_items:
  - anki.desktop

# Add-ons used:
# https://ankiweb.net/shared/info/2055492159
# https://ankiweb.net/shared/info/208879074
