---
- name: Update apt's cache
  become: true
  # update cache once a day
  apt: update_cache=true cache_valid_time=86400

- name: Install apt-file
  become: true
  apt: name=apt-file state=latest

- name: Register apt-file change time
  # local time (secs since Epoch) minus
  # the folder's last change time (secs since Epoch)
  shell: echo $((`date +%s`-`stat /var/cache/apt/apt-file/ -c%Z`))
  register: ctime
  changed_when: false

- name: Update apt-file's cache
  become: true
  # update once a month
  command: apt-file update
  when: ctime.stdout|int > 2592000

- name: Remove unneeded stuff
  become: true
  apt: name={{item}} state=absent purge=true
  with_items:
  - aptitude
  - banshee
  - cowsay
  - fortune
  - mono-runtime
  - tomboy
  - totem

- name: Add trusty-backports ubuntu repo (for jq-1.4)
  become: true
  apt_repository: repo='deb http://archive.ubuntu.com/ubuntu trusty-backports main universe'
                  state=present

- name: Add Chrome signing key
  become: true
  apt_key: url=https://dl-ssl.google.com/linux/linux_signing_key.pub
           state=present
           validate_certs=true

- name: Add Chrome repo
  become: true
  apt_repository: repo='deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main'
                  state=present

- name: Install common stuff
  become: true
  apt: name={{item}} state=latest
  with_items:
  - alien # rpm to deb
  - ansible
  - apache2-utils # ab, rotatelogs
  - autokey-gtk
  - build-essential
  - curl
  - dia
  - dia-shapes
  - dos2unix
  - dropbox
  - emacs
  - expect
  - gdb
  - git
  - giggle
  - gnuplot
  - gnuplot-x11 # conflicts with gnuplot-nox
  - google-chrome-stable
  - graphviz
  - graphviz-doc
  - gsfonts-x11 # dia recommends
  - hexdiff
  - htop
  - inotify-tools
  - jq
  - kcachegrind
  - kdelibs-bin      # to fix kde apps crashes
  - kdelibs5-data    # to fix kde apps crashes
  - kdelibs5-plugins # to fix kde apps crashes
  - keepassx
  - libxml2-utils # provides xmllint
  - mc
  - meld
  - mercurial
  - moreutils # for errno
  - mpg321 # for mpg123 :)
  - mscgen # http://www.mcternan.me.uk/mscgen/index.html
  - nmap
  - nmon
  - python-gpgme
  - pwgen
  - rdesktop
  - skype
  - software-properties-common # add-apt-repository
  - spell
  - sysbench
  - sysstat # iostat
  - sysv-rc-conf
  - tig
  - tree
  - uuid
  - valgrind
  - vino     # VNC server
  - vinagre  # VNC client
  - vlc
  - vpnc
  - wget
  - whois
  - wireshark

- name: Use correct time zone
  become: true
  file: src=/usr/share/zoneinfo/Europe/Minsk
        dest=/etc/localtime
        state=link
        force=true

- name: Install NTP
  become: true
  apt: name={{item}} state=latest
  with_items:
  - ntp
  - ntpdate

- name: Start NTP
  become: true
  service: name=ntp
           enabled=true
           state=started

- name: Install SSH
  become: true
  apt: name={{item}} state=latest
  with_items:
  - openssh-client
  - openssh-server

- name: Start SSH
  become: true
  service: name=ssh
           enabled=true
           state=started

- name: Symlink 'refs'
  file: src=/home/{{user}}/Dropbox/refs
        dest=/home/{{user}}/refs
        state=link
        force=true

- name: Copy global configs
  become: true
  copy: src=files/configs/global/{{item.name}}
        dest={{item.path}}/{{item.name}}
        backup=true
  with_items:
  - {name: locale, path: /etc/default/}

- name: Copy local configs
  copy: src=files/configs/local/{{item}}
        dest=/home/{{user}}/{{item}}
        backup=true
  with_items:
  - .bashrc
  - .gitconfig
  - .Xmodmap

- name: Copy host specific configs
  copy: src=files/configs/local/{{item}}
        dest=/home/{{user}}/{{item}}
        force=false
  with_items:
  - .bashrc.local

- name: Create user's bin dir
  file: path=/home/{{user}}/bin
        state=directory

- name: Copy generic scripts
  copy: src=files/scripts/{{item}}
        dest=/home/{{user}}/bin/{{item}}
        mode=0755
        backup=true
  with_items:
  - capslock-to-control.sh
  - flip-args
  - fmon.sh
  - gtag
  - meld
  - pjson
  - pxml
  - rerl
  - tags

- name: Ensure user's config autostart exists
  file: path=/home/{{user}}/.config/autostart
        state=directory

- name: Copy generic autostart configs
  copy: src=files/configs/local/{{item}}
        dest=/home/{{user}}/.config/autostart/{{item}}
        backup=true
  with_items:
  - autokey.desktop
  - capslock-to-control.desktop
  - my-dropbox.desktop

- name: Pull emacs repo
  git: repo=git@github.com:ten0s/emacs
       dest=/home/{{user}}/emacs

- name: Create link to .emacs
  file: src=/home/{{user}}/emacs/emacs
        dest=/home/{{user}}/.emacs
        state=link

- name: Pull autokey repo
  git: repo=git@github.com:ten0s/autokey
       dest=/home/{{user}}/.config/autokey
       force=true
