---
- name: Create projects dir
  file: path={{item}}
        state=directory
  with_items:
  - /home/{{user}}/projects
  - /home/{{user}}/projects/tmp

- name: Update /etc/security/limits.conf file
  become: true
  lineinfile: dest=/etc/security/limits.conf
              insertbefore='# End of file'
              line='ten0s hard nofile 40960'
              state=present

- name: Update /etc/pam.d/su file
  become: true
  lineinfile: dest=/etc/pam.d/su
              regexp="^session    required   pam_limits.so"
              insertafter='^# session    required   pam_limits.so'
              line="session    required   pam_limits.so"
              state=present

- name: Install Flex & Bison
  become: true
  apt: name={{item}} state=present
  with_items:
  - bison
  - bison-doc
  - flex
  - flex-doc
