---
- name: Pull emacs repo
  git: repo=git@github.com:ten0s/emacs
       dest=/home/{{user}}/emacs

- name: Create link to .emacs
  file: src=/home/{{user}}/emacs/emacs
        dest=/home/{{user}}/.emacs
        state=link
