---
- name: Install Erlang's deps
  sudo: true
  apt: name={{item}} state=latest
  with_items:
  - build-essential
  - default-jdk
  - fop
  - libglu1-mesa-dev
  - libncurses5-dev
  - libssl-dev
  - libtk-img-dev
  - libwxgtk2.8-dev
  - unixodbc-dev
  - xsltproc
