---
- name: Create libs dirs
  file: path={{item}}
        state=directory
  with_items:
  - /home/{{user}}/.erl_libs
  - /home/{{user}}/.erl_libs/ebin

- name: Install Erlang's deps
  become: true
  apt: name={{item}} state=latest
  with_items:
  - build-essential
  - default-jdk
  - fop
  - libglu1-mesa-dev
  - libncurses5-dev
  - libssl-dev
  - libtk-img-dev
  - libwxgtk2.8-dev
  - unixodbc-dev
  - xsltproc

- name: Install kerl
  get_url: url=https://raw.githubusercontent.com/yrashk/kerl/master/kerl
           dest=/home/{{user}}/bin/
           mode=0755

- name: Provision kerl config
  copy: src=configs/local/.kerlrc
        dest=/home/{{user}}/.kerlrc
        backup=true

- name: Update Erlang versions
  command: kerl update releases

- name: Delete Erlang installations
  become: true
  command: >
    kerl delete installation /opt/{{item}}
    removes=/opt/{{item}}
  with_items:
  - r16b03-1
  - r18.1
  - r18.2

- name: Delete Erlang builds
  command: >
    kerl delete build {{item}}
    removes=/home/{{user}}/.kerl/builds/{{item}}
  with_items:
  - r16b03-1
  - r18.1
  - r18.2

- name: Delete Dialyzer lookup tables
  file: path=/home/{{user}}/.{{item}}.plt
        state=absent
  with_items:
  - r16b03-1
  - r18.1
  - r18.2

- name: Build Erlang versions
  command: >
    kerl build {{item.release}} {{item.name}}
    creates=/home/{{user}}/.kerl/builds/{{item.name}}
  with_items:
  - {release: '18.3', name: 'r18.3'}

- name: Install Erlang versions
  command: sudo kerl install {{item}} creates=/opt/{{item}}
  with_items:
  - 'r18.3'

- name: Build Dialyzer lookup tables
  shell: >
    source /opt/{{item}}/activate && dialyzer --build_plt
    --output_plt /home/{{user}}/.{{item}}.plt
    --apps kernel stdlib erts crypto public_key mnesia sasl common_test eunit
    ssh ssl asn1 compiler syntax_tools tools inets snmp xmerl
    creates=/home/{{user}}/.{{item}}.plt
  args:
     executable: /bin/bash
  register: dialyzer_result
  failed_when: dialyzer_result.rc == 1
  with_items:
  - 'r18.3'

- name: Pull user_default repo
  git: repo=git@github.com:ten0s/user_default.git
       dest=/home/{{user}}/projects/user_default
       version=HEAD

- name: Build user_default
  command: erlc user_default.erl chdir=/home/{{user}}/projects/user_default/

- name: Create user_default link
  file: src=/home/{{user}}/projects/user_default/user_default.beam
        dest=/home/{{user}}/.erl_libs/ebin/user_default.beam
        state=link

- name: Pull sync repo
  git: repo=https://github.com/rustyio/sync.git
       dest=/home/{{user}}/.erl_libs/sync
       version=11df81d

- name: Build sync
  command: make chdir=/home/{{user}}/.erl_libs/sync/

- name: Pull eper repo
  git: repo=https://github.com/massemanet/eper.git
       dest=/home/{{user}}/.erl_libs/eper
       version=0.97.3

- name: Build eper
  command: make chdir=/home/{{user}}/.erl_libs/eper/

- name: Provision .erlang config
  copy: src=configs/local/.erlang
        dest=/home/{{user}}/.erlang
        backup=true

- name: Pull syntaxerl repo
  git: repo=git@github.com:ten0s/syntaxerl.git
       dest=/home/{{user}}/projects/syntaxerl
       version=HEAD

- name: Build syntaxerl
  command: make chdir=/home/{{user}}/projects/syntaxerl/

- name: Create syntaxerl link
  file: src=/home/{{user}}/projects/syntaxerl/syntaxerl
        dest=/home/{{user}}/bin/syntaxerl
        state=link

- name: Pull rebar repo
  git: repo=https://github.com/rebar/rebar.git
       dest=/home/{{user}}/projects/rebar
       version=2.6.1

- name: Build rebar
  command: ./bootstrap chdir=/home/{{user}}/projects/rebar/

- name: Create rebar link
  file: src=/home/{{user}}/projects/rebar/rebar
        dest=/home/{{user}}/bin/rebar
        state=link

- name: Pull erlang-history
  git: repo=https://github.com/ferd/erlang-history.git
       dest=/home/{{user}}/projects/erlang-history
       version=HEAD

- name: Make erlang-history
  command: make chdir=/home/{{user}}/projects/erlang-history

- name: Install erlang-history to current Erlang release
  become: true
  command: make install chdir=/home/{{user}}/projects/erlang-history
