---
- name: Install Erlang's deps
  become: true
  apt: name={{item}} state=latest
  with_items:
  - build-essential
  - default-jdk
  - fop
  - libglu1-mesa-dev
  - libncurses5-dev
  - libssl-dev
  - libtk-img-dev
  - libwxgtk2.8-dev
  - unixodbc-dev
  - xsltproc

- name: Install kerl
  get_url: url=https://raw.githubusercontent.com/yrashk/kerl/master/kerl
           dest=/home/{{user}}/bin/
           mode=0755

- name: Provision kerl config
  copy: src=configs/local/.kerlrc
        dest=/home/{{user}}/.kerlrc
        backup=true

- name: Update Erlang versions
  command: kerl update releases

- name: Build Erlang versions
  command: kerl build {{item.release}} {{item.name}} creates=/home/{{user}}/.kerl/builds/{{item.name}}
  with_items:
  - {release: '18.1', name: 'r18.1'}

- name: Install Erlang versions
  command: sudo kerl install {{item}} creates=/opt/{{item}}
  with_items:
  - 'r18.1'

- name: Pull syntaxerl repo
  git: repo=https://github.com/ten0s/syntaxerl.git
       dest=/home/{{user}}/projects/syntaxerl
       version=HEAD

- name: Build syntaxerl
  command: make chdir=/home/{{user}}/projects/syntaxerl/

- name: Create syntaxerl link
  file: src=/home/{{user}}/projects/syntaxerl/syntaxerl
        dest=/home/{{user}}/bin/syntaxerl
        state=link

- name: Pull rebar repo
  git: repo=https://github.com/rebar/rebar.git
       dest=/home/{{user}}/projects/rebar
       version=2.6.1

- name: Build rebar
  command: ./bootstrap chdir=/home/{{user}}/projects/rebar/

- name: Create rebar link
  file: src=/home/{{user}}/projects/rebar/rebar
        dest=/home/{{user}}/bin/rebar
        state=link

- name: Pull erlang-history
  git: repo=https://github.com/ferd/erlang-history.git
       dest=/home/{{user}}/projects/erlang-history
       version=HEAD

- name: Make erlang-history
  command: make chdir=/home/{{user}}/projects/erlang-history

- name: Install erlang-history to current Erlang release
  become: true
  command: make install chdir=/home/{{user}}/projects/erlang-history
