---
- name: Uninstall HP #1
  become: true
  apt: name={{item}} state=absent
  with_items:
  - haskell-platform
  - haskell-platform-doc
  - haskell-platform-prof
  - ghc

- name: Uninstall HP #2
  file: path=/home/{{user}}/{{item}} state=absent
  with_items:
  - .cabal
  - .ghc

# https://docs.haskellstack.org/en/stable/README/
- name: Install Stack
  shell: curl -sSL https://get.haskellstack.org/ | sh creates=/usr/local/bin/stack

- name: Update Stack
  command: stack update

- name: Setup GHC
  command: stack setup

# ensure ~/.local/bin: in PATH

# https://github.com/koalaman/shellcheck
- name: Install ShellCheck
  command: stack install ShellCheck

# https://github.com/idris-lang/Idris-dev/blob/master/INSTALL.md
- name: Install Idris
  command: stack install idris
