---
- name: Install deps
  become: true
  apt: name={{item}} state=latest
  with_items:
  - build-essential
  - libffi-dev
  - libgmp3-dev

# https://docs.haskellstack.org/en/stable/README/
- name: Install Stack
  shell: curl -sSL https://get.haskellstack.org/ | sh creates=/usr/local/bin/stack

- name: Update Stack
  command: stack update

# stack ghci
- name: Setup GHC
  command: stack setup

# ensure ~/.local/bin: in PATH

# https://github.com/koalaman/shellcheck
- name: Install ShellCheck
  command: stack install ShellCheck

# https://github.com/idris-lang/Idris-dev/blob/master/INSTALL.md
- name: Install Idris
  command: stack install idris
