---
##
# http://tecadmin.net/install-oracle-java-8-jdk-8-ubuntu-via-ppa/
##

# https://launchpad.net/~webupd8team/+archive/ubuntu/java
- name: Add Java Ubuntu key
  become: true
  apt_key: keyserver=keyserver.ubuntu.com
           id=EEA14886
           state=present

- name: Add Java Ubuntu repo
  become: true
  apt_repository: repo='deb http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main'
                  state=present

# http://www.webupd8.org/2012/09/install-oracle-java-8-in-ubuntu-via-ppa.html
- name: Enable automated installation
  shell: echo oracle-java9-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections

- name: Install Java 8 Installer
  become: true
  apt: name=oracle-java8-installer
       state=present

- name: Set Java 8 as default
  become: true
  apt: name=oracle-java8-set-default
       state=present

##
# sudo update-alternatives --config java
# sudo update-alternatives --config javac
##
