---
- name: Create dirs
  file: path="{{item}}"
        state=directory
  with_items:
  - /home/{{user}}/.java_libs

##
# http://tecadmin.net/install-oracle-java-8-jdk-8-ubuntu-via-ppa/
##

# https://launchpad.net/~webupd8team/+archive/ubuntu/java
- name: Add Java Ubuntu key
  become: true
  apt_key: keyserver=keyserver.ubuntu.com
           id=EEA14886
           state=present

- name: Add Java Ubuntu repo
  become: true
  apt_repository: repo='deb http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main'
                  state=present

# http://www.webupd8.org/2012/09/install-oracle-java-8-in-ubuntu-via-ppa.html
- name: Enable automated installation
  shell: echo oracle-java9-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections

- name: Install Java 8 Installer
  become: true
  apt: name=oracle-java8-installer
       state=present

- name: Set Java 8 as default
  become: true
  apt: name=oracle-java8-set-default
       state=present

##
# https://maven.apache.org/download.cgi
##

- name: Install Maven 1/4
  become: true
  apt: name=maven
       state=absent
       purge=true

- name: Install Maven 2/4
  get_url:
    url=http://mirror.cogentco.com/pub/apache/maven/maven-3/{{mvn_ver}}/binaries/apache-maven-{{mvn_ver}}-bin.tar.gz
    dest={{cache_dir}}/apache-maven-{{mvn_ver}}-bin.tar.gz

- name: Install Maven 3/4
  unarchive:
    src={{cache_dir}}/apache-maven-{{mvn_ver}}-bin.tar.gz
    dest=/home/{{user}}/.java_libs/

- name: Install Maven 4/4
  file: src=/home/{{user}}/.java_libs/apache-maven-{{mvn_ver}}/bin/mvn
        dest=/home/{{user}}/bin/mvn
        state=link

##
# sudo update-alternatives --config java
# sudo update-alternatives --config javac
##
