- name: Setup `megalodon` scripts
  copy: src=files/scripts/{{item}}
        dest=/home/{{user}}/bin/{{item}}
        mode=0755
  with_items:
  - add-monitor.sh

- name: Copy `megalodon` autostart configs
  copy: src=files/configs/local/{{item}}
        dest=/home/{{user}}/.config/autostart/{{item}}
  with_items:
  - add-monitor.desktop
