---
##
# https://help.ubuntu.com/community/Oracle%20Instant%20Client
##

# Download RPMs from http://www.oracle.com/technetwork/topics/linuxx86-64soft-092277.html

- name: Install Oracle client
  become: true
  command: >
           alien -c -i /home/{{user}}/refs/db/oracle/{{item.rpm}}
           creates={{item.creates}}
  with_items:
  - {rpm: oracle-instantclient12.1-basic-12.1.0.2.0-1.x86_64.rpm,
     creates: /usr/lib/oracle/12.1/client64}
  - {rpm: oracle-instantclient12.1-devel-12.1.0.2.0-1.x86_64.rpm,
     creates: /usr/include/oracle/12.1/client64}
  - {rpm: oracle-instantclient12.1-sqlplus-12.1.0.2.0-1.x86_64.rpm,
     creates: /usr/bin/sqlplus64}

- name: Copy ld.so config
  become: true
  copy: src=files/configs/global/oracle.conf
        dest=/etc/ld.so.conf.d/oracle.conf
  register: oracle_conf

- name: Run ldconfig
  become: true
  command: ldconfig
  when: oracle_conf | changed

- name: Define ORACLE_HOME
  become: true
  copy: src=files/configs/global/oracle.sh
        dest=/etc/profile.d/oracle.sh

- name: Fix SDK 1/2
  become: true
  file: path=/usr/lib/oracle/12.1/client64/rdbms
        state=directory

- name: Fix SDK 2/2
  become: true
  file: src=/usr/include/oracle/12.1/client64
        dest=/usr/lib/oracle/12.1/client64/{{item}}
        state=link
  with_items:
  - include
  - rdbms/public

- name: Configure SQL*Plus
  copy: src=files/configs/local/login.sql
        dest=/home/{{user}}/login.sql

# http://www.oracle.com/technetwork/developer-tools/sql-developer/overview/index.html

- name: Install SQL Developer
  become: true
  command: >
           alien -c -i /home/{{user}}/refs/db/oracle/sqldeveloper-4.1.3.20.78-1.noarch.rpm
           creates=/opt/sqldeveloper/sqldeveloper.sh
  register: sqldeveloper

- debug: msg='Now run /opt/sqldeveloper/sqldeveloper.sh and enter "/usr/lib/jvm/java-8-oracle"'
  when: sqldeveloper | changed
