---
- name: Install Python's dev deps
  become: true
  apt: name={{item}} state=present
  with_items:
  - build-essential
  - python-dev
  - python-setuptools

- name: Install pip
  become: true
  easy_install: name=pip

- name: Install virtualenv
  become: true
  pip: name=virtualenv

- name: Install ansible-lint
  become: true
  pip: name=ansible-lint

- name: Install SciPy stack
  # http://www.scipy.org/install.html
  become: true
  apt: name={{item}} state=present
  with_items:
  - python-dev
  - python-numpy
  - python-scipy
  - python-pandas
  - python-sympy
  - python-nose
  - python-matplotlib
  - python-networkx
  - python-tk
  - ipython
  - ipython-notebook
  - ipython-qtconsole

- name: Install bumpversion
  become: true
  pip: name=bumpversion

- name: Install pywinrm
  become: true
  pip: name=http://github.com/diyan/pywinrm/archive/master.zip#egg=pywinrm
