---
- name: Install Python's dev deps
  become: true
  apt: name={{item}} state=present
  with_items:
  - build-essential
  - python-dev
  - python-pip
  - python3-pip
  - python-setuptools

- name: Upgrade pip
  become: true
  command: pip install --upgrade pip
  register: pip_upgrade
  changed_when: "'Successfully installed' in pip_upgrade.stdout"

- name: Install virtualenv
  become: true
  pip: name=virtualenv

- name: Install ansible-lint
  become: true
  pip: name=ansible-lint

#  fonts-font-awesome fonts-mathjax ipython-notebook-common libjs-highlight
#  libjs-jquery-ui libjs-marked libjs-mathjax python-simplegeneric python-zmq
- name: Install Jupyter
  become: true
  pip: name=jupyter

# https://github.com/takluyver/bash_kernel
- name: Install IBash kernel 1/2
  become: true
  pip: name=bash_kernel

- name: Install IBash kernel 2/2
  become: true
  command: python -m bash_kernel.install

# http://graphviz.readthedocs.io/en/latest/manual.html
- name: Install Graphviz
  become: true
  pip: name=graphviz

- name: Install gvmagic 1/2
  git: repo=https://github.com/cjdrake/ipython-magic.git
       dest=/home/{{user}}/projects/ipython-gvmagic
       version=HEAD

- name: Install gvmagic 2/2
  become: true
  command: python setup.py install chdir=/home/{{user}}/projects/ipython-gvmagic

- name: Install SciPy stack
  # http://www.scipy.org/install.html
  become: true
  apt: name={{item}} state=present
  with_items:
  - python-numpy
  - python-scipy
  - python-pandas
  - python-sympy
  - python-nose
  - python-matplotlib
  - python-networkx
  - python-tk

- name: Upgrade SymPy
  become: true
  command: pip install -U sympy

- name: Install iPyWidgets
  become: true
  command: pip install -U ipywidgets

- name: Enable iPyWidgets
  become: true
  command: jupyter nbextension enable --py --sys-prefix widgetsnbextension

- name: Install bumpversion
  become: true
  pip: name=bumpversion

- name: Install pywinrm
  become: true
  pip: name=http://github.com/diyan/pywinrm/archive/master.zip#egg=pywinrm

# http://docs.aws.amazon.com/cli/latest/userguide/installing.html#install-with-pip
- name: Install AWSCLI
  become: true
  pip: name=awscli

# Requirement for EC2 modules (see Install AWSCLI)
- name: Install Boto
  become: true
  pip: name=boto

- name: Install Boto3
  become: true
  pip: name=boto3

- name: Install Hypothesis
  become: true
  pip: name=hypothesis

- name: Install PyTest
  become: true
  pip: name=pytest

- name: Install json2yaml
  become: true
  pip: name=json2yaml

- name: Install youtube-dl
  become: true
  pip: name=youtube-dl
