---
- name: Install Python's dev deps
  become: true
  apt: name={{item}} state=present
  with_items:
  - build-essential
  - python-dev
  - python-pip
  - python3-pip
  - python-setuptools

- name: Upgrade pip
  become: true
  command: pip install --upgrade pip
  register: pip_upgrade
  changed_when: "'Successfully installed' in pip_upgrade.stdout"

- name: Install virtualenv
  become: true
  pip: name=virtualenv

- name: Install ansible-lint
  become: true
  pip: name=ansible-lint

- name: Install Jupyter
  become: true
  pip: name=jupyter

# https://github.com/takluyver/bash_kernel
- name: Install IBash kernel 1/2
  become: true
  pip: name=bash_kernel

- name: Install IBash kernel 2/2
  become: true
  command: python -m bash_kernel.install

 # http://graphviz.readthedocs.io/en/latest/manual.html
- name: Install Graphviz
  become: true
  pip: name=graphviz

- name: Install SciPy stack
  # http://www.scipy.org/install.html
  become: true
  apt: name={{item}} state=present
  with_items:
  - python-dev
  - python-numpy
  - python-scipy
  - python-pandas
  - python-sympy
  - python-nose
  - python-matplotlib
  - python-networkx
  - python-tk

- name: Install bumpversion
  become: true
  pip: name=bumpversion

- name: Install pywinrm
  become: true
  pip: name=http://github.com/diyan/pywinrm/archive/master.zip#egg=pywinrm
