---
- name: Ensure python dev deps are installed
  sudo: yes
  apt: name={{item}} state=present
  with_items:
  - build-essential
  - python-dev
  - python-setuptools

- name: Ensure pip is installed
  sudo: yes
  easy_install: name=pip

- name: Ensure virtualenv is installed
  sudo: yes
  pip: name=virtualenv

- name: Ensure SciPy stack is installed
  # http://www.scipy.org/install.html
  sudo: yes
  apt: name={{item}} state=present
  with_items:
  - python-dev
  - python-numpy
  - python-scipy
  - python-pandas
  - python-sympy
  - python-nose
  - python-matplotlib
  - python-networkx
  - python-tk
  - ipython
  - ipython-notebook
