---
- name: Install Python's dev deps
  sudo: true
  apt: name={{item}} state=present
  with_items:
  - build-essential
  - python-dev
  - python-setuptools

- name: Install pip
  sudo: true
  easy_install: name=pip

- name: Install virtualenv
  sudo: true
  pip: name=virtualenv

- name: Install ansible-lint
  sudo: true
  pip: name=ansible-lint

- name: Install SciPy stack
  # http://www.scipy.org/install.html
  sudo: true
  apt: name={{item}} state=present
  with_items:
  - python-dev
  - python-numpy
  - python-scipy
  - python-pandas
  - python-sympy
  - python-nose
  - python-matplotlib
  - python-networkx
  - python-tk
  - ipython
  - ipython-notebook
