---
- name: Remove Scala 2.9.2
  become: true
  apt: name={{item}} state=removed
  with_items:
  - scala
  - scala-doc

#
# Install Scala Build Tool (sbt)
#
- name: Add sbt Ubuntu key
  become: true
  apt_key: keyserver=keyserver.ubuntu.com
           id=2EE0EA64E40A89B84B2DF73499E82A75642AC823
           state=present

- name: Add sbt Ubuntu repo
  become: true
  apt_repository: repo='deb https://dl.bintray.com/sbt/debian /'
                  state=present

- name: Install sbt
  become: true
  apt: name=sbt state=latest
