---
- name: Create download cache dir
  sudo: true
  file: path={{cache_dir}}
        state=directory
        mode=0777

- name: Download Vagrant package
  get_url: url=https://releases.hashicorp.com/vagrant/{{vagrant_ver}}/vagrant_{{vagrant_ver}}_x86_64.deb
           dest={{cache_dir}}/vagrant-{{vagrant_ver}}.deb

- name: Install Vagrant
  sudo: true
  apt: deb={{cache_dir}}/vagrant-{{vagrant_ver}}.deb
       state=present

- name: Register `vagrant plugin list` output
  shell: vagrant plugin list
  register: vagrant_plugin_list
  changed_when: false

- name: Install Vagrant's plugins
  # https://github.com/mitchellh/vagrant/wiki/Available-Vagrant-Plugins
  shell: vagrant plugin install {{item}}
  with_items:
  - vagrant-vbguest
  - vagrant-vbox-snapshot
  - vagrant-winrm
  when: "'{{item}}' not in vagrant_plugin_list.stdout"

- name: Update Vagrant's plugins
  shell: vagrant plugin update
  register: vagrant_plugin_update
  changed_when: "'Updated' in vagrant_plugin_update.stdout"

#
# TODO: Setup apt source
# https://www.virtualbox.org/wiki/Linux_Downloads
#

- name: Install Virtualbox
  sudo: true
  apt: name=virtualbox-{{vbox_ver}} state=present
