---
- name: Ensure download cache dir is created
  sudo: yes
  file: >
    path={{cache_dir}}
    state=directory
    mode=0777

- name: Download Vagrant package
  get_url: >
    url=https://dl.bintray.com/mitchellh/vagrant/vagrant_{{vagrant_ver}}_x86_64.deb
    dest={{cache_dir}}/vagrant-{{vagrant_ver}}.deb

- name: Ensure Vagrant is installed
  sudo: yes
  apt: >
    deb={{cache_dir}}/vagrant-{{vagrant_ver}}.deb
    state=present

- name: Register `vagrant plugin list` output
  shell: vagrant plugin list
  register: plugins
  changed_when: false

- name: Ensure Vagrant's plugins are installed
  # https://github.com/mitchellh/vagrant/wiki/Available-Vagrant-Plugins
  shell: vagrant plugin install {{item}}
  with_items:
  - vagrant-vbguest
  - vagrant-vbox-snapshot
  when: "'{{item}}' not in plugins.stdout"

#
# TODO: Setup apt source
# https://www.virtualbox.org/wiki/Linux_Downloads
#

- name: Ensure Virtualbox is installed
  sudo: yes
  apt: name=virtualbox-{{vbox_ver}} state=latest
