---
- name: Install deps
  apt: name={{item}}
       state=present
  with_items:
  - libmozjs185-dev

- name: Add apt key
  become: true
  apt_key: keyserver=keyserver.ubuntu.com
           id=C17EAB57
           state=present

- name: Add apt repo
  become: true
  apt_repository: repo='deb https://apache.bintray.com/couchdb-deb bionic main'
                  state=present
