---
- name: Set vars
  set_fact:
    anki2_ver: 2.1.22-linux-amd64

- name: Symlink $HOME/anki2
  file: src=/home/{{user}}/Dropbox/refs/anki2
        dest=/home/{{user}}/anki2
        state=link
        force=true

- name: Install deps
  become: true
  apt:
    name:
    - dvipng
    - texlive-latex-base
    state: present

- name: Install 1/5
  get_url: url=https://apps.ankiweb.net/downloads/current/anki-{{anki2_ver}}.tar.bz2
           dest={{cache_dir}}/anki-{{anki2_ver}}.tar.bz2

- name: Install 2/5
  unarchive: src={{cache_dir}}/anki-{{anki2_ver}}.tar.bz2
             dest=/home/{{user}}/tmp/
             creates=/home/{{user}}/tmp/anki-{{anki2_ver}}
  register: anki

- name: Install 3/5
  become: true
  command: make install chdir=/home/{{user}}/tmp/anki-{{anki2_ver}}/
  when: anki.changed

- name: Install 4/5
  copy: src={{item}}
        dest=/home/{{user}}/bin/{{item}}
        mode=0755
  with_items:
  - anki-dropbox-sync.sh

- name: Install 5/5
  copy: src={{item}}
        dest=/home/{{user}}/.local/share/applications/{{item}}
        backup=true
  with_items:
  - anki.desktop

# Add-ons used:
# https://ankiweb.net/shared/info/1463041493
# https://ankiweb.net/shared/info/2055492159
# https://ankiweb.net/shared/info/208879074
