---
- set_fact:
    handlers:
    - {scheme: djvux, desktop: djvux.desktop, handler: evincex.sh}
    - {scheme: manx , desktop: manx.desktop , handler: manx.sh}
    - {scheme: pdfx , desktop: pdfx.desktop , handler: evincex.sh}

- name: Symlink $HOME/anki2
  file: src=/home/{{user}}/Dropbox/refs/anki2
        dest=/home/{{user}}/anki2
        state=link
        force=true

- name: MIME associations 1/3
  copy: src={{item.desktop}}
        dest=/home/{{user}}/.local/share/applications/{{item.desktop}}
        backup=true
  with_items:
  - "{{handlers}}"

- name: MIME associations 2/3
  copy: src={{item.handler}}
        dest=/home/{{user}}/bin/{{item.handler}}
        mode=0755
  with_items:
  - "{{handlers}}"

- name: MIME associations 3/3
  lineinfile:
    path: /home/{{user}}/.local/share/applications/mimeapps.list
    backup: true
    regexp: "x-scheme-handler/{{item.scheme}}={{item.desktop}}"
    insertafter: "^[Added Associations]"
    line: "x-scheme-handler/{{item.scheme}}={{item.desktop}};"
    state: present
  with_items:
  - "{{handlers}}"

- name: Install deps
  become: true
  apt:
    name:
    - dvipng
    - texlive-latex-base
    state: present

- name: Install 1/5
  get_url: url=https://apps.ankiweb.net/downloads/current/anki-{{anki2_ver}}.tar.bz2
           dest={{cache_dir}}/anki-{{anki2_ver}}.tar.bz2

- name: Install 2/5
  unarchive: src={{cache_dir}}/anki-{{anki2_ver}}.tar.bz2
             dest=/home/{{user}}/tmp/
             creates=/home/{{user}}/tmp/anki-{{anki2_ver}}
  register: anki

- name: Install 3/5
  become: true
  command: make install chdir=/home/{{user}}/tmp/anki-{{anki2_ver}}/
  when: anki.changed

- name: Install 4/5
  copy: src={{item}}
        dest=/home/{{user}}/bin/{{item}}
        mode=0755
  with_items:
  - anki-dropbox-sync.sh

- name: Install 5/5
  become: true
  copy: src={{item}}
        dest=/usr/local/share/applications/{{item}}
        backup=true
  with_items:
  - anki.desktop

# Add-ons used:
# https://ankiweb.net/shared/info/2055492159
# https://ankiweb.net/shared/info/208879074
