---
- name: Set vars
  set_fact:
    clang_ver: 15
    gcc_ver: 12

- name: Install deps
  become: true
  apt:
    name:
    - autoconf
    - autoconf-archive
    - automake
    - cmake
    state: latest

- name: Install Clang
  become: true
  apt:
    name:
    - clang-{{clang_ver}}
    state: latest

- name: Install Gcc
  become: true
  apt:
    name:
    - gcc-{{gcc_ver}}
    - g++-{{gcc_ver}}
    - gcc-multilib # for -m32
    - g++-multilib
    state: latest

- name: Install static checkers
  become: true
  apt:
    name:
    - cppcheck # Tool for static C/C++ code analysis
    - splint   # A tool for statically checking C programs
    state: latest

# $ sudo update-alternatives --config c++
- name: Install Clang as main c++ alternative
  become: true
  command: update-alternatives --install {{item.link}} {{item.name}} {{item.path}} {{item.prio}}
  with_items:
  - {link: '/usr/bin/cc' , name: 'cc' , path: '/usr/bin/clang-{{clang_ver}}', prio: 50}
  - {link: '/usr/bin/c++', name: 'c++', path: '/usr/bin/clang++-{{clang_ver}}', prio: 50}
  - {link: '/usr/bin/cc' , name: 'cc' , path: '/usr/bin/gcc-{{gcc_ver}}', prio: 70}
  - {link: '/usr/bin/c++', name: 'c++', path: '/usr/bin/g++-{{gcc_ver}}', prio: 70}

- name: Copy bashrc config
  template: src=10-bashrc-cpp.j2
            dest=/home/{{user}}/.bashrc.d/10-bashrc-cpp

- name: Install Boost
  become: true
  apt:
    name:
    - libboost-all-dev
    - libboost-doc # /usr/share/doc/libboost1.74-doc/
    state: latest

# https://github.com/google/googletest/tree/main/googletest
# https://developer.ibm.com/articles/au-googletestingframework/
# $ pkg-config --cflags --libs gtest
- name: Install Google Test
  become: true
  apt:
    name:
    - googletest
    - libgtest-dev
    state: latest

# GTK C++
# sudo apt install libgtkmm-3.0-{dev,doc}
