---
- name: Set vars
  set_fact:
    clang_ver: 10
    gcc_ver: 9

- name: Install deps
  become: true
  apt:
    name:
    - autoconf
    - autoconf-archive
    - automake
    state: present

- name: Install Clang
  become: true
  apt:
    name:
    - clang-{{clang_ver}}
    - llvm
    state: present

- name: Install Gcc
  become: true
  apt:
    name:
    - gcc-{{gcc_ver}}
    state: present

## sudo update-alternatives --config c++
- name: Install Clang as main c++ alternative
  become: true
  command: update-alternatives --install {{item.link}} {{item.name}} {{item.path}} 100
  with_items:
  - {link: '/usr/bin/cc' , name: 'cc' , path: '/usr/bin/clang-{{clang_ver}}'}
  - {link: '/usr/bin/c++', name: 'c++', path: '/usr/bin/clang++-{{clang_ver}}'}

- name: Install Boost
  become: true
  apt: name=libboost-all-dev
       state=present

#- name: Download Boost
#  get_url: url=http://sourceforge.net/projects/boost/files/boost/1.41.0/boost_1_41_0.tar.gz
#           dest=/tmp/boost_1_41_0.tar.gz

#
# https://en.cppreference.com/w/Cppreference:Archives
#
- name: Install C and C++ standard library reference for Devhelp
  become: true
  apt: name=cppreference-doc-en-html
       state=present
