---
- name: Set vars
  set_fact:
    clang_ver: 10
    gcc_ver: 9

- name: Install deps
  become: true
  apt:
    name:
    - autoconf
    - autoconf-archive
    - automake
    state: present

- name: Install Clang
  become: true
  apt:
    name:
    - clang-{{clang_ver}}
    - llvm
    state: present

- name: Install Gcc
  become: true
  apt:
    name:
    - gcc-{{gcc_ver}}
    state: present

# $ sudo update-alternatives --config c++
- name: Install Clang as main c++ alternative
  become: true
  command: update-alternatives --install {{item.link}} {{item.name}} {{item.path}} 100
  with_items:
  - {link: '/usr/bin/cc' , name: 'cc' , path: '/usr/bin/clang-{{clang_ver}}'}
  - {link: '/usr/bin/c++', name: 'c++', path: '/usr/bin/clang++-{{clang_ver}}'}

- name: Copy bashrc config
  template: src=10-bashrc-cpp.j2
            dest=/home/{{user}}/.bashrc.d/10-bashrc-cpp

- name: Install Boost
  become: true
  apt: name=libboost-all-dev
       state=latest

# https://github.com/google/googletest/tree/main/googletest
# https://developer.ibm.com/articles/au-googletestingframework/
# $ pkg-config --cflags --libs gtest
- name: Install Google Test
  become: true
  apt:
    name:
    - googletest
    - libgtest-dev
    state: latest

# https://en.cppreference.com/w/Cppreference:Archives
- name: Install C and C++ standard library reference for Devhelp
  become: true
  apt: name=cppreference-doc-en-html
       state=present
