---
##
# https://code.visualstudio.com/docs/setup/linux#_debian-and-ubuntu-based-distributions
##

- name: Add apt key
  become: true
  apt_key: url=https://packages.microsoft.com/keys/microsoft.asc
           state=present

- name: Add apt repo
  become: true
  apt_repository: repo='deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main'
                  state=present

- name: Install
  become: true
  apt: name=code
       state=present
