#!/data/data/com.termux/files/usr/bin/bash

if ! pidof sshd; then
    termux-wake-lock
    timeout --kill-after=61m 60m sshd -D -e
    ret=$?
    case $ret in
    124)
        termux-notification -c "sshd terminated after timeout ($ret)"
        ;;
    137)
        termux-notification -c "sshd killed after timeout ($ret)"
        ;;
    *)
        termux-notification -c "sshd stopped ($ret)"
        ;;
    esac
    termux-wake-unlock
fi
