---
- name: Git Pull Wiki
  cron:
    name: "Git Pull Wiki"
    special_time: "reboot"
    job: "(cd ~/projects/wiki && git pull origin master)"
    state: absent

- name: Git Push Wiki
  cron:
    name: "Git Push Wiki"
    minute: "*/5"
    job: "(cd ~/projects/wiki && git add index.html && git commit -m 'Auto-saved' ; git remote | xargs -I{} git push {} master)"
    state: absent

- name: RSync Wiki
  cron:
    name: "RSync Wiki"
    minute: "*/5"
    job: "(cd ~/Dropbox/wiki && rsync -avh --log-file=/tmp/rsync-wiki.log ./ serverpi:/media/Transcend/Public/wiki/)"

- name: Git Push Wiki Recipes
  cron:
    name: "Git Push Wiki Recipes"
    minute: "*/5"
    job: "(cd ~/projects/recipes && git add index.html && git commit -m 'Auto-saved' ; git remote | xargs -I{} git push {} master)"

- name: RSync Wiki Gym
  cron:
    name: "RSync Wiki Gym"
    minute: "*/5"
    job: "(cd ~/projects/wiki-gym && rsync -avh --log-file=/tmp/rsync-wiki-gym.log ./ serverpi:/media/Transcend/Public/wiki-gym/)"
