---
- name: Set vars
  set_fact:
    termux_bin: /data/data/com.termux/files/usr/bin

- name: Install tools
  become: true
  apt:
    name:
    - aapt
    - adb
    - apktool
    state: present

- name: Copy local scripts
  copy: src={{item}}
        dest=/home/{{user}}/bin/{{item}}
        mode=0755
        backup=true
  with_items:
  - phone-sshfs

- name: Install phone curl
  connection: ssh
  delegate_to: phone
  command: pkg install -y curl

- name: Install phone ffmpeg
  connection: ssh
  delegate_to: phone
  command: pkg install -y ffmpeg

- name: Install phone htop
  connection: ssh
  delegate_to: phone
  command: pkg install -y htop

- name: Install phone git
  connection: ssh
  delegate_to: phone
  command: pkg install -y git

- name: Install phone manpages
  connection: ssh
  delegate_to: phone
  command: pkg install -y manpages

- name: Install phone mc
  connection: ssh
  delegate_to: phone
  command: pkg install -y mc

- name: Install phone netcat-openbsd
  connection: ssh
  delegate_to: phone
  command: pkg install -y netcat-openbsd

- name: Install phone which
  connection: ssh
  delegate_to: phone
  command: pkg install -y which

- name: Install phone yt-dlp
  connection: ssh
  delegate_to: phone
  command: pip install -U yt-dlp

- name: Install phone Termux:GUI Python bindings
  connection: ssh
  delegate_to: phone
  command: pip install -U termuxgui

- name: Install phone Termux:GUI C/C++ bindings
  connection: ssh
  delegate_to: phone
  command: pkg install -y termux-gui-c

- name: Install phone Termux:GUI utils
  connection: ssh
  delegate_to: phone
  command: pkg install -y termux-gui-package

- name: Install phone Node.js
  connection: ssh
  delegate_to: phone
  command: pkg install -y nodejs-lts

- name: Install phone HTTP Server
  connection: ssh
  delegate_to: phone
  command: npm install -g http-server

# https://www.reddit.com/r/termux/comments/12c3fvp/sh_1_httpserver_not_found_when_trying_to_run_a/
- name: Install phone tudo
  connection: ssh
  delegate_to: phone
  shell: >
    curl -sL https://github.com/agnostic-apollo/tudo/releases/latest/download/tudo -o "{{termux_bin}}/tudo" &&
    chmod 755 "{{termux_bin}}/tudo"

- name: Create phone dirs
  connection: ssh
  delegate_to: phone
  file: path={{item.path}}
        mode=0755
        state=directory
  with_items:
  - {path: .shortcuts/tasks}
  - {path: bin}
  - {path: log}
  - {path: tmp}

- name: Copy phone scripts
  connection: ssh
  delegate_to: phone
  copy: src={{item.src}}
        dest={{item.dest}}
        mode=0755
        #backup=true
  with_items:
  - {src: phone/dot_bashrc                       , dest: .bashrc}
  - {src: phone/dot_gitconfig                    , dest: .gitconfig}
  - {src: phone/bin/termux-url-opener            , dest: bin}
  - {src: phone/shortcuts/tasks/pkg-upgrade      , dest: .shortcuts/tasks}
  - {src: phone/shortcuts/tasks/sshd-start       , dest: .shortcuts/tasks}
  - {src: phone/shortcuts/tasks/sshd-stop        , dest: .shortcuts/tasks}
  - {src: phone/shortcuts/tasks/wiki-open        , dest: .shortcuts/tasks}
  - {src: phone/shortcuts/tasks/wiki-pull        , dest: .shortcuts/tasks}
  - {src: phone/shortcuts/tasks/wiki-start-global, dest: .shortcuts/tasks}
  - {src: phone/shortcuts/tasks/wiki-start-local , dest: .shortcuts/tasks}
  - {src: phone/shortcuts/tasks/wiki-stop        , dest: .shortcuts/tasks}
