---
- name: Install tools
  become: true
  apt:
    name:
    - aapt
    - adb
    - apktool
    state: present

- name: Copy local scripts
  copy: src={{item}}
        dest=/home/{{user}}/bin/{{item}}
        mode=0755
        backup=true
  with_items:
  - phone-sshfs

- name: Install phone deps
  connection: ssh
  delegate_to: phone
  command: pkg install manpages htop

- name: Create phone dirs
  connection: ssh
  delegate_to: phone
  file: path={{item.path}}
        mode=0755
        state=directory
  with_items:
  - {path: bin}
  - {path: .shortcuts/tasks}

- name: Copy phone scripts
  connection: ssh
  delegate_to: phone
  copy: src={{item.src}}
        dest={{item.dest}}
        mode=0755
        #backup=true
  with_items:
  - {src: phone/bin/termux-url-opener     , dest: bin}
  - {src: phone/shortcuts/tasks/sshd-start, dest: .shortcuts/tasks}
  - {src: phone/shortcuts/tasks/sshd-stop , dest: .shortcuts/tasks}
  - {src: phone/shortcuts/wiki-open       , dest: .shortcuts}
  - {src: phone/shortcuts/tasks/wiki-pull , dest: .shortcuts/tasks}
  - {src: phone/shortcuts/tasks/wiki-start, dest: .shortcuts/tasks}
  - {src: phone/shortcuts/tasks/wiki-stop , dest: .shortcuts/tasks}
