---
- name: Set vars
  set_fact:
    termux_bin: /data/data/com.termux/files/usr/bin

- name: Install tools
  become: true
  apt:
    name:
    - aapt
    - adb
    - apktool
    state: present

- name: Copy local scripts
  copy: src={{item}}
        dest=/home/{{user}}/bin/{{item}}
        mode=0755
        backup=true
  with_items:
  - phone-sshfs

- name: Install phone deps
  connection: ssh
  delegate_to: phone
  command: pkg install curl htop manpages nodejs-lts which

- name: Install phone HTTP Server
  connection: ssh
  delegate_to: phone
  command: npm install -g http-server

# https://www.reddit.com/r/termux/comments/12c3fvp/sh_1_httpserver_not_found_when_trying_to_run_a/
- name: Install phone tudo
  connection: ssh
  delegate_to: phone
  shell: >
    curl -sL https://github.com/agnostic-apollo/tudo/releases/latest/download/tudo -o "{{termux_bin}}/tudo" &&
    chmod 755 "{{termux_bin}}/tudo"

- name: Create phone dirs
  connection: ssh
  delegate_to: phone
  file: path={{item.path}}
        mode=0755
        state=directory
  with_items:
  - {path: bin}
  - {path: log}
  - {path: .shortcuts/tasks}

- name: Copy phone scripts
  connection: ssh
  delegate_to: phone
  copy: src={{item.src}}
        dest={{item.dest}}
        mode=0755
        #backup=true
  with_items:
  - {src: phone/bin/termux-url-opener            , dest: bin}
  - {src: phone/shortcuts/tasks/pkg-upgrade      , dest: .shortcuts/tasks}
  - {src: phone/shortcuts/tasks/sshd-start       , dest: .shortcuts/tasks}
  - {src: phone/shortcuts/tasks/sshd-stop        , dest: .shortcuts/tasks}
  - {src: phone/shortcuts/tasks/wiki-open        , dest: .shortcuts/tasks}
  - {src: phone/shortcuts/tasks/wiki-pull        , dest: .shortcuts/tasks}
  - {src: phone/shortcuts/tasks/wiki-start-global, dest: .shortcuts/tasks}
  - {src: phone/shortcuts/tasks/wiki-start-local , dest: .shortcuts/tasks}
  - {src: phone/shortcuts/tasks/wiki-stop        , dest: .shortcuts/tasks}
