---
#
# https://github.com/nvm-sh/nvm
# https://github.com/nvm-sh/nvm#git-install
#

- name: Pull NVM
  git: repo=https://github.com/nvm-sh/nvm.git
       dest=/home/{{user}}/.nvm
       version=v0.38.0

- name: Copy bashrc config
  copy: src=01-bashrc-nvm
        dest=/home/{{user}}/.bashrc.d/10-bashrc-nvm

#
# $ nvm ls-remote --lts
# $ nvm ls
# $ nvm alias default VERSION
# $ nvm use VERSION
#

- name: Install new Node.js
  shell: |
    source /home/{{user}}/.bashrc
    nvm install {{item}}
  args:
    creates: "/home/{{user}}/.nvm/versions/node/{{item}}/bin"
    executable: /bin/bash
  with_items:
  - v10.24.0
  - v12.22.0

- name: Set default Node.js
  shell: |
    source /home/{{user}}/.bashrc
    nvm alias default {{nodejs_ver}}
  args:
    executable: /bin/bash

- name: Uninstall old Node.js
  shell: |
    source /home/{{user}}/.bashrc
    nvm uninstall {{item}}
  args:
    executable: /bin/bash
  with_items:
  - v10.22.1
  - v12.19.0

#
# sudo npm install --global <PACKAGE>@<VERSION>
#

- name: Install NPM global packages
  become: true
  npm:
    name: "{{item.name}}"
    version: "{{item.version}}"
    global: true
    state: latest
    executable: "/home/{{user}}/.nvm/versions/node/{{nodejs_ver}}/bin/npm"
  with_items:
  - {name: "jslint", version: "0.12.1"}
  - {name: "yarn",   version: "1.22.10"}
