#!/usr/bin/env python3
# -*- mode: python -*-

# Setup Env
# $ ./setup-env.sh

# Enter Env
# $ source env/bin/activate

# Run
# $ ./ws-events

import os
import asyncio
import json
import websockets

WS_URL = os.getenv("WS_URL")

def ws_events(url, recv_timeout=900):
    async def events():
        print(f"Connecting to {url}")
        async with websockets.connect(url) as ws:
            print(f"Waiting for events from {url}")
            while True:
                rep = None
                try:
                    rep = await asyncio.wait_for(ws.recv(), timeout=recv_timeout)
                    print(rep)
                except asyncio.TimeoutError:
                    print("Timeout")
                    break
    loop = asyncio.get_event_loop()
    loop.run_until_complete(events())

ws_events(WS_URL)
