---
- name: Install deps
  become: true
  apt:
    name:
    - build-essential
    - libffi-dev
    - libgmp3-dev
    state: latest

# https://docs.haskellstack.org/en/stable/README/
- name: Install Stack
  shell: curl -sSL https://get.haskellstack.org/ | sh creates=/usr/local/bin/stack

- name: Update Stack
  command: stack update

# stack ghci
- name: Setup GHC
  command: stack setup
