- name: Copy scripts
  copy: src={{item}}
        dest=/home/{{user}}/bin/{{item}}
        mode=0755
        backup=true
  with_items:
  - add-monitor.sh
  - rabbitmq-delete-all
  - rabbitmq-list-all
  - rabbitmq-list-nempty
  - rabbitmq-purge-all
  - start-alley-env
  - start-alley-test-env
  - watch-rmq-queues

- name: Copy autostart configs
  copy: src={{item}}
        dest=/home/{{user}}/.config/autostart/{{item}}
        backup=true
  with_items:
  - add-monitor.desktop
