---
#
# https://github.com/realworldocaml/book/wiki/Installation-Instructions
#

# https://launchpad.net/~avsm/+archive/ubuntu/ppa
- name: Add apt repo
  become: true
  apt_repository: repo="{{item}}"
                  state=present
  with_items:
  - "deb http://ppa.launchpad.net/avsm/ppa/ubuntu {{ubuntu_codename}} main"
  - "deb-src http://ppa.launchpad.net/avsm/ppa/ubuntu {{ubuntu_codename}} main"

- name: Install deps
  become: true
  apt: name={{item}} state=latest
  with_items:
  - darcs
  - libffi-dev
  - libssl-dev
  - m4
  - mercurial
  - ocaml
  - ocaml-doc
  - ocaml-mode
  - ocaml-native-compilers
  - opam
  - tuareg-mode
  - zlib1g-dev
  - libzmq3-dev # for iocaml

- name: Configure OPAM
  command: opam init --auto-setup creates=~/.opam/

- name: Help message
  debug: msg='Open a new terminal if below installation of OPAM packages fails'

- name: Update OPAM
  command: opam update

- name: Install packages
  command: opam install -y {{item}}
  register: opam_result
  changed_when: not ("Package {{item}} is already installed" in opam_result.stderr)
  with_items:
  - core
  - utop
  - async
  - yojson
  - core_extended
  - core_bench
  - cohttp
  - sexplib
  - async_graphics
  - async_ssl
  - cryptokit
  - menhir
  - atdgen
  - textwrap
  - ssl
  - websocket
  - iocaml

- name: Configure utop (1/6)
  lineinfile: dest=~/.ocamlinit line="#use \"topfind\";;"

- name: Configure utop (2/6)
  lineinfile: dest=~/.ocamlinit line="#thread;;"

- name: Configure utop (3/6)
  lineinfile: dest=~/.ocamlinit line="#camlp4o;;"

- name: Configure utop (4/6)
  lineinfile: dest=~/.ocamlinit line="#require \"core.syntax\";;"

- name: Configure utop (4/6)
  lineinfile: dest=~/.ocamlinit line="open Core.Std;;"

- name: Configure utop (4/6)
  lineinfile: dest=~/.ocamlinit line="#require \"core.top\";;"
