---
- name: Set vars
  set_fact:
    cmake_ver: 3.29.3

- name: Cleanup
  become: true
  apt:
    name: cmake
    state: absent

- name: Download
  get_url:
    url="https://github.com/Kitware/CMake/releases/download/v{{cmake_ver}}/cmake-{{cmake_ver}}-linux-x86_64.sh"
    dest="{{cache_dir}}/cmake-{{cmake_ver}}-linux-x86_64.sh"

- name: Install
  become: true
  command: "bash {{cache_dir}}/cmake-{{cmake_ver}}-linux-x86_64.sh --skip-license --prefix=/usr/local"
