---
- name: Set vars
  set_fact:
    # $ curl -s --head https://download.teamviewer.com/download/linux/teamviewer_amd64.deb | grep location
    teamviewer_ver: 15.31.5

- name: Download
  get_url: url=https://dl.teamviewer.com/download/linux/version_15x/teamviewer_{{teamviewer_ver}}_amd64.deb
           dest={{cache_dir}}/teamviewer_{{teamviewer_ver}}_amd64.deb

- name: Install
  become: true
  apt: deb={{cache_dir}}/teamviewer_{{teamviewer_ver}}_amd64.deb
       state=present

- name: Enable
  become: true
  service: name=teamviewerd
           enabled=true
           state=started
