---
- name: Install deps
  become: true
  apt:
    name:
    - libaio1
    state: latest

##
# https://help.ubuntu.com/community/Oracle%20Instant%20Client
##

# Download Instant Client RPMs from
# https://www.oracle.com/database/technologies/instant-client/linux-x86-64-downloads.html
# and SQL Developer RPM from
# http://www.oracle.com/technetwork/developer-tools/sql-developer/overview/index.html
# to {{cache_dir}}

- name: Check RPMs exists 1/5
  stat:
    path: "{{cache_dir}}/oracle-instantclient12.1-basic-12.1.0.2.0-1.x86_64.rpm"
  register: basic_result

- name: Check RPMs exists 2/5
  stat:
    path: "{{cache_dir}}/oracle-instantclient12.1-devel-12.1.0.2.0-1.x86_64.rpm"
  register: devel_result

- name: Check RPMs exists 3/5
  stat:
    path: "{{cache_dir}}/oracle-instantclient12.1-sqlplus-12.1.0.2.0-1.x86_64.rpm"
  register: sqlplus_result

- name: Check RPMs exists 4/5
  stat:
    path: "{{cache_dir}}/sqldeveloper-19.2.1.247.2212.noarch.rpm"
  register: sqldeveloper_result

- name: Check RPMs exists 5/5
  assert:
    that:
      - basic_result.stat.exists
      - devel_result.stat.exists
      - sqlplus_result.stat.exists
      - sqldeveloper_result.stat.exists
    fail_msg: "Please download RPMs to {{cache_dir}}"

- name: Install RPM to DEB
  become: true
  apt: name=alien state=latest

- name: Install Oracle client
  become: true
  command: >
           alien -c -i {{cache_dir}}/{{item.rpm}}
           creates={{item.creates}}
  with_items:
  - {rpm: oracle-instantclient12.1-basic-12.1.0.2.0-1.x86_64.rpm,
     creates: /usr/lib/oracle/12.1/client64}
  - {rpm: oracle-instantclient12.1-devel-12.1.0.2.0-1.x86_64.rpm,
     creates: /usr/include/oracle/12.1/client64}
  - {rpm: oracle-instantclient12.1-sqlplus-12.1.0.2.0-1.x86_64.rpm,
     creates: /usr/bin/sqlplus64}

- name: Copy ld.so config
  become: true
  copy: src=oracle.conf
        dest=/etc/ld.so.conf.d/oracle.conf
  register: oracle_conf

- name: Run ldconfig
  become: true
  command: ldconfig
  when: oracle_conf.changed

- name: Define ORACLE_HOME
  become: true
  copy: src=oracle.sh
        dest=/etc/profile.d/oracle.sh

- name: Fix SDK 1/2
  become: true
  file: path=/usr/lib/oracle/12.1/client64/rdbms
        state=directory

- name: Fix SDK 2/2
  become: true
  file: src=/usr/include/oracle/12.1/client64
        dest=/usr/lib/oracle/12.1/client64/{{item}}
        state=link
  with_items:
  - include
  - rdbms/public

- name: Configure SQL*Plus
  copy: src=login.sql
        dest=/home/{{user}}/login.sql

- name: Install SQL Developer
  become: true
  command: >
           alien -c -i {{cache_dir}}/sqldeveloper-19.2.1.247.2212.noarch.rpm
           creates=/opt/sqldeveloper/sqldeveloper.sh
  register: sqldeveloper

- debug: msg='Now run /opt/sqldeveloper/sqldeveloper.sh and enter "/usr/lib/jvm/java-8-oracle"'
  when: sqldeveloper.changed

- name: Uninstall RPM to DEB
  become: true
  apt:
    name:
    - alien
    - rpm
    state: absent
    purge: true
