---
- name: Install deps
  become: true
  apt:
    name:
    - build-essential
    - libxml2-dev
    - libxslt-dev
    - python-dev
    - python-pip
    - python3-dev
    - python3-pip
    - python3-venv
    state: present

- name: Upgrade pip
  become: true
  pip:
    name: pip
    state: latest

- name: Install virtualenv
  pip:
    name: virtualenv
    extra_args: --user
    state: latest

- name: Install ansible-lint
  pip:
    name: ansible-lint
    extra_args: --user
    state: latest

- name: Install Boto3
  pip:
    name: boto3
    extra_args: --user
    state: latest
