---
- name: Install deps
  become: true
  apt:
    name:
    - build-essential
    - libxml2-dev
    - libxslt-dev
    - python-dev
    - python-pip
    - python3-dev
    - python3-pip
    - python3-venv
    state: present

- name: Upgrade pip
  become: true
  pip: name=pip state=latest
  register: pip_upgrade
  changed_when: "'Successfully installed' in pip_upgrade.stdout"

- name: Install virtualenv
  become: true
  pip: name=virtualenv

- name: Install ansible-lint
  become: true
  pip: name=ansible-lint

- name: Install Boto3
  become: true
  pip: name=boto3 state=latest
