---
- name: Install
  become: true
  apt: name=emacs
       state=latest

- name: Create dir
  file: path=/home/{{user}}/emacs
        state=directory

- name: Copy libs
  copy: src=lib
        dest=/home/{{user}}/emacs

- name: Copy .emacs config
  copy: src=dot_emacs
            dest=/home/{{user}}/.emacs

- name: Copy bashrc config
  copy: src=01-bashrc-emacs
        dest=/home/{{user}}/.bashrc.d/
