---
- set_fact:
    filetypes:
    - {type: "text/x-org", file: "text-x-org.xml"}

##
# After clean install run M-x list-packages
##

- name: Install
  become: true
  apt: name=emacs
       state=latest

- name: Create dir
  file: path=/home/{{user}}/emacs
        state=directory

- name: Copy libs
  copy: src=lib
        dest=/home/{{user}}/emacs

- name: Copy .emacs config
  template: src=dot_emacs.j2
            dest=/home/{{user}}/.emacs
            backup=true

- name: Copy bashrc config
  copy: src=01-bashrc-emacs
        dest=/home/{{user}}/.bashrc.d/
        backup=true

#
# Copies MIME-TYPE.xml to
# ${XDG_DATA_HOME:-$HOME/.local/share}/mime/packages/
# like the below command does
# $ xdg-mime install PATH/TO/MIME-TYPE.xml
#
- name: Copy filetypes
  copy: src={{item.file}}
        dest=/home/{{user}}/.local/share/mime/packages/
        backup=true
  with_items:
  - "{{filetypes}}"

#
# Adds 'TYPE=emacs.desktop' to
# ${XDG_CONFIG_HOME:-$HOME/.config}/mimeapps.list
# under '[Default Applications]'
# $ xdg-mime query filetype PATH/TO/FILE.org
# text/x-org
# $ xdg-mime query default text/x-org
# emacs.desktop
#
- name: Register MIME types
  command: xdg-mime default emacs.desktop {{item.type}}
  with_items:
  - "{{filetypes}}"

- name: Update MIME database
  command: update-mime-database /home/{{user}}/.local/share/mime
