---
- name: Download
  get_url: url=https://zoom.us/client/latest/zoom_amd64.deb
           dest={{cache_dir}}/zoom_amd64.deb

- name: Install
  become: true
  apt: deb={{cache_dir}}/zoom_amd64.deb
       state=present
