#!/usr/bin/env bash

PROG=$(basename $0)

if [[ $# -ne 2 ]]; then
    echo "Usage: $PROG <HEADER> <CONST>"
    echo "Print value of CONST defined in HEADER"
    echo "Example:"
    echo "$ $PROG dlfcn.h RTLD_LAZY"
    echo "RTLD_LAZY: 1"
    echo "$ $PROG sys/stat.h 'O_WRONLY|O_CREAT|O_APPEND'"
    echo "O_WRONLY|O_CREAT|O_APPEND: 1089"
    exit 1
fi

HEADER=$1
CONST=$2
TMP_SRC=`mktemp --suffix .cpp`
TMP_OUT=`mktemp`

sed -e "s;{{HEADER}};$HEADER;" -e "s;{{CONST}};$CONST;g"  << EOF > $TMP_SRC
#include <iostream>
#include <iomanip>
#include "{{HEADER}}"
using namespace std;
int main() {
    cout << fixed << setprecision(18)
         << "{{CONST}}" << ": " << ({{CONST}})
         << endl;
}
EOF

g++ $TMP_SRC -o -I$PWD $TMP_OUT && $TMP_OUT
rm -f $TMP_SRC $TMP_OUT
