#!/usr/bin/env bash

PROG=$(basename $0)

if [[ $# -ne 2 ]]; then
    echo "Usage: $PROG <HEADER> <CONST>"
    echo "Print value of CONST defined in HEADER"
    echo "Example:"
    echo "$ $PROG dlfcn.h RTLD_LAZY"
    echo "RTLD_LAZY: 1"
    exit 1
fi

HEADER=$1
CONST=$2
TMP_SRC=`mktemp --suffix .c`
TMP_OUT=`mktemp`

sed -e "s/{{HEADER}}/$HEADER/" -e "s/{{CONST}}/$CONST/g"  << EOF > $TMP_SRC
#include <stdio.h>
#include "{{HEADER}}"
void main() {
    printf("%s: %d\n", "{{CONST}}", {{CONST}});
}
EOF

gcc $TMP_SRC -o $TMP_OUT && $TMP_OUT
rm -f $TMP_SRC $TMP_OUT
