#!/bin/bash

# https://github.com/envygeeks/jekyll-docker

# usage:
# $ jekyll --help
# $ jekyll new <name>
# $ jekyll build
# $ jekyll serve

opts[k++]=-it
opts[k++]=--rm
opts[k++]=--volume="$PWD:/srv/jekyll"
if [[ `echo $@ | grep serve` ]]; then
    opts[k++]=--publish=4000:4000
fi

export JEKYLL_VERSION=3.8
docker run ${opts[@]} jekyll/jekyll:$JEKYLL_VERSION jekyll "$@"
