#!/usr/bin/env bash

if [[ $# -ne 1 ]]; then
    echo "Usage: $(basename $0) <FILE>"
    echo "See also stat(1), stat(2), chattr(1) and inode(7)"
    exit 1
fi

FILE="$1"

if [[ ! -e $FILE ]]; then
    echo "$FILE: No such file or directory"
    exit 2
fi

RAW_MODE_BIN=$(bc <<EOF
ibase=16
obase=2
$(stat --format='%f' $FILE | tr 'abcdef' 'ABCDEF')
EOF
)
RAW_MODE_STR=$(printf '%16s' $RAW_MODE_BIN)

ATTR=$(lsattr $FILE | cut -d' ' -f1)

DEV=$(stat --format='%d' $FILE)
DEV_MAJOR=$(($DEV >> 8))
DEV_MINOR=$(($DEV - ($DEV_MAJOR << 8)))

RDEV_MAJOR=$(bc <<EOF
ibase=16
obase=A
$(stat --format='%t' $FILE)
EOF
)
RDEV_MINOR=$(bc <<EOF
ibase=16
obase=A
$(stat --format='%T' $FILE)
EOF
)

stat $FILE --printf="\
File name        : %n ( %N )
File size        : %s bytes
File type        : %F ( $RDEV_MAJOR:$RDEV_MINOR )
Access           : 0o%04a ( %16A )
Raw mode         : 0x%f ( $RAW_MODE_STR )
Attr             : (  $ATTR )
Uid              : %u ( %U )
Gid              : %g ( %G )
Device ID        : %d ( $DEV_MAJOR:$DEV_MINOR )
Inode number     : %i
Hard links       : %h
Mount point      : %m
Allocated blocks : %b
Block size       : %B bytes
Optimal IO block : %o bytes
Access time      : %X ( %x )
Modify time      : %Y ( %y )
Change time      : %Z ( %z )
Birth time       : %W ( %w )
"
