#!/usr/bin/env bash

if [[ $# -ne 1 ]]; then
    echo "Usage: $(basename $0) <FILE>"
    echo "See also stat(1), stat(2), statx(2) and inode(7)"
    exit 1
fi

FILE="$1"

RAW_MODE_BIN=$(bc <<EOF
ibase=16
obase=2
$(stat --format='%f' $FILE | tr 'abcdef' 'ABCDEF')
EOF
)
RAW_MODE_STR=$(printf '%16s' $RAW_MODE_BIN)

DEV=$(stat --format='%d' $FILE)
DEV_MAJOR=$(($DEV >> 8))
DEV_MINOR=$(($DEV - ($DEV_MAJOR << 8)))

RDEV_MAJOR=$(bc <<EOF
ibase=16
obase=A
$(stat --format='%t' $FILE)
EOF
)
RDEV_MINOR=$(bc <<EOF
ibase=16
obase=A
$(stat --format='%T' $FILE)
EOF
)

stat $FILE --printf="\
File name        : %n ( %N )
File size        : %s bytes
File type        : %F
Access           : 0o%04a ( %16A )
Raw mode         : 0x%f ( $RAW_MODE_STR )
Uid              : %u ( %U )
Gid              : %g ( %G )
Inode            : %i
Device number    : $DEV_MAJOR:$DEV_MINOR ( %d )
Device type      : $RDEV_MAJOR:$RDEV_MINOR
Hard links       : %h
Mount point      : %m
Allocated blocks : %b
Block size       : %B bytes
Optimal IO block : %o bytes
Access time      : %X ( %x )
Modify time      : %Y ( %y )
Change time      : %Z ( %z )
Birth time       : %W ( %w )
"
