#!/usr/bin/env bash

if [[ $# -ne 1 ]]; then
    echo "Usage: $(basename $0) <FILE>"
    echo "See also stat(1), stat(2) and statx(2)"
    exit 1
fi

FILE="$1"

RAW_MODE_BIN=$(bc <<EOF
ibase=16
obase=2
$(stat --format='%f' $FILE | tr 'abcdef' 'ABCDEF')
EOF
)

RAW_MODE_STR=$(printf '%16s' $RAW_MODE_BIN)

stat $FILE --printf="\
File name        : %n ( %N )
File size        : %s bytes
File type        : %F
Access           : 0o%04a ( %16A )
Raw mode         : 0x%f ( $RAW_MODE_STR )
Uid              : %u ( %U )
Gid              : %g ( %G )
Inode            : %i
Mount point      : %m
Allocated blocks : %b
Block size       : %B bytes
Optimal IO block : %o bytes
Device number    : 0x%D ( %d )
Device type      : %t %T
Hard links       : %h
Access time      : %X ( %x )
Modify time      : %Y ( %y )
Change time      : %Z ( %z )
Birth time       : %W ( %w )
"
