#!/usr/bin/env bash

PROG=$(basename $0)

if [[ $# -ne 2 ]]; then
    echo "Usage: $PROG <HEADER> <CONST>"
    echo "Print value of CONST defined in HEADER"
    echo "Example:"
    echo "$ $PROG wincrypt.h CALG_DH_EPHEM"
    echo "CALG_DH_EPHEM: 43522"
    echo "$ $PROG wincrypt.h 'ALG_CLASS_KEY_EXCHANGE | ALG_TYPE_DH | ALG_SID_DH_EPHEM'"
    echo "ALG_CLASS_KEY_EXCHANGE | ALG_TYPE_DH | ALG_SID_DH_EPHEM: 43522"
    exit 1
fi

HEADER=$1
CONST=$2
TMP_SRC=`mktemp --suffix .cpp`
TMP_OUT=`mktemp`

sed -e "s;{{HEADER}};$HEADER;" -e "s;{{CONST}};$CONST;g"  << EOF > $TMP_SRC
#include <stdio.h>
#include <windows.h>
#include "{{HEADER}}"
void print(const char *n, const char *s) { printf("%s: %s\n", n, s); }
void print(const char *n, int i)         { printf("%s: %ld | 0x%lx\n", n, i, i); }
void print(const char *n, long int i)    { printf("%s: %ld | 0x%lx\n", n, i, i); }
void print(const char *n, double d)      { printf("%s: %.20lf\n", n, d); }
int main() {
    print("{{CONST}}", ({{CONST}}));
}
EOF

CPATH=$PWD:$CPATH x86_64-w64-mingw32-g++ $TMP_SRC -o $TMP_OUT && WINEDEBUG=-all wine $TMP_OUT
rm -f $TMP_SRC $TMP_OUT
