---
- name: Copy scripts
  copy: src={{item}}
        dest=/home/{{user}}/bin/{{item}}
        mode=0755
        backup=true
  with_items:
  - describe-ec2.sh
  - jenkins-build.sh
  - open-aws-accounts.sh
  - terminate-ec2.sh
  - to-table.sh
