---
#
# https://nodejs.org/en/about/releases
# https://github.com/nodesource/distributions
#
- name: Remove Node.js 6.x apt repo
  become: true
  apt_repository:
    repo="deb https://deb.nodesource.com/node_6.x {{ubuntu_codename}} main"
    state=absent

#- name: Remove old Node.js
#  become: true
#  apt: name=nodejs
#       state=absent

- name: Add Node.js apt key
  become: true
  shell: curl -sL https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add -

- name: Add Node.js 10.x apt repo
  become: true
  apt_repository:
    repo="deb https://deb.nodesource.com/node_10.x {{ubuntu_codename}} main"
    state=present

- name: Install Node.js
  become: true
  apt: name=nodejs
       state=latest

# sudo npm install --global <PACKAGE>
- name: Install NPM global packages
  become: true
  npm: name={{item.name}}
       version={{item.version}}
       global=true
       state=present
  with_items:
  - {name: "commander", version: "4.1.1"}
  - {name: "jslint", version: "0.12.1"}
  - {name: "qunit", version: "2.9.3"}
  - {name: "yarn", version: "1.22.0"}
