---
#
# https://nodejs.org/en/about/releases
# https://github.com/nodesource/distributions
#

- name: Remove old Node.js
  become: true
  apt: name=nodejs state=absent

- name: Remove old Node.js repos
  become: true
  apt_repository: repo={{item}} state=absent
  with_items:
  - "deb https://deb.nodesource.com/node_6.x {{ubuntu_codename}} main"
  - "deb https://deb.nodesource.com/node_8.x {{ubuntu_codename}} main"
  - "deb https://deb.nodesource.com/node_10.x {{ubuntu_codename}} main"

#
# https://github.com/nvm-sh/nvm
#

- name: Install NVM
  shell: >
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.36.0/install.sh | bash
  args:
    creates: "/home/{{user}}/.nvm/nvm.sh"

- name: Copy bashrc config
  copy: src=01-bashrc-nvm
        dest=/home/{{user}}/.bashrc.d/10-bashrc-nvm

#
# $ nvm ls-remote --lts
# $ nvm ls
#

- name: Install Node.js
  shell: |
    source /home/{{user}}/.bashrc
    nvm install {{item}}
  args:
    creates: "/home/{{user}}/.nvm/versions/node/{{item}}/bin"
    executable: /bin/bash
  with_items:
  - v10.22.1
  - v12.19.0

#
# sudo npm install --global <PACKAGE>@<VERSION>
#

- name: Install NPM global packages
  become: true
  npm: name={{item.name}}
       version={{item.version}}
       global=true
       state=latest
  with_items:
  - {name: "jslint", version: "0.12.1"}
  - {name: "yarn",   version: "1.22.4"}
