---
#
# https://nodejs.org/en/about/releases
# https://github.com/nodesource/distributions
#
- name: Add Node.js apt key
  become: true
  shell: curl -sL https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add -

- name: Remove old Node.js
  become: true
  apt: name=nodejs state=absent

- name: Remove old Node.js repos
  become: true
  apt_repository: repo={{item}} state=absent
  with_items:
  - "deb https://deb.nodesource.com/node_6.x {{ubuntu_codename}} main"
  - "deb https://deb.nodesource.com/node_8.x {{ubuntu_codename}} main"

- name: Add new Node.js repo
  become: true
  apt_repository:
    repo="deb https://deb.nodesource.com/node_10.x {{ubuntu_codename}} main"
    state=present

- name: Install Node.js
  become: true
  apt: name=nodejs state=latest

# sudo npm install --global <PACKAGE>@<VERSION>
- name: Install NPM global packages
  become: true
  npm: name={{item.name}}
       version={{item.version}}
       global=true
       state=latest
  with_items:
  - {name: "eslint", version: "7.2.0"}
  - {name: "jslint", version: "0.12.1"}
  - {name: "qunit",  version: "2.10.0"}
  - {name: "yarn",   version: "1.22.4"}
