---
- name: Install
  become: true
  apt: name=winehq-stable
       state=present
  register: wine

- debug: msg='Now run Wine -> Configure Wine and install everything it will ask'
  when: wine is changed
