---
#
# https://wiki.winehq.org/Ubuntu
#

- name: Add i386 arch
  become: true
  command: dpkg --add-architecture i386

- name: Add apt key
  become: true
  apt_key:
    url: https://dl.winehq.org/wine-builds/winehq.key
    state: present
    validate_certs: true

- name: Add apt repo
  become: true
  apt_repository:
    repo: 'deb https://dl.winehq.org/wine-builds/ubuntu/ {{ubuntu_codename}} main'
    state: present

- name: Install utils
  become: true
  apt:
    name:
    - mingw-w64
    - mingw-w64-tools
    - msitools        # msiextract
    state: latest

# See https://wiki.winehq.org/Ubuntu for 'Ubuntu 22.04 and Wine stable'
# See https://forum.winehq.org/viewtopic.php?t=36232 for 'Wine is too slow'

# Maybe needed for having winscard.dll
# $ sudo apt install pcscd pcsc-tools libpcsclite1

#wine-stable-i386
#wine-stable-amd64
#winehq-stable
#wine-stable
#wine-stable-dev

- name: Install
  become: true
  apt:
    name:
    - winbind
    - winehq-stable   # stable | devel
    - wine-stable-dev # headers
    install_recommends: true
    state: latest
  register: wine

- debug: msg='Now run Wine -> Configure Wine (winecfg) and install everything it will ask'
  when: wine is changed
