---
- name: Install
  become: true
  apt:
    name:
    - mingw-w64
    - winehq-stable
    state: latest
  register: wine

- debug: msg='Now run Wine -> Configure Wine and install everything it will ask'
  when: wine is changed
