- name: Add apt repo
  become: true
  apt_repository: repo='ppa:ubuntu-wine/ppa'
                  state=present

- name: Install
  become: true
  apt: name=wine1.7
       state=present
  register: wine

- debug: msg='Now run Wine -> Configure Wine and install everything it will ask'
  when: wine | changed
