---

#
#- name: Install Jupyter Lab
#  pip:
#    name: jupyterlab
#    extra_args: --user
#    state: latest
#    executable: pip3

#
# https://jupyter.org/install
# https://github.com/jupyter-xeus/xeus-cling
# https://xeus-cling.readthedocs.io/en/latest/index.html
# See 'Install Mamba + Jupyter + Xeus-Cling'
#

#
# https://pypi.org/project/bash_kernel/
#
- name: Install Bash Kernel 1/2
  pip:
    name: bash_kernel
    extra_args: --user
    state: latest
    executable: pip3

- name: Install Bash Kernel 2/2
  shell: python3 -m bash_kernel.install

- name: Copy bashrc config
  copy: src=10-bashrc-jupyter
        dest=/home/{{user}}/.bashrc.d/

- name: Copy desktop
  copy: src=jupyter-lab.desktop
        dest=/home/{{user}}/.local/share/applications/
        backup=true
