---
#
# https://jupyter.org/install
#
- name: Install Jupyter Lab
  pip:
    name: jupyterlab
    extra_args: --user
    state: latest
    executable: pip3

#
# https://pypi.org/project/bash_kernel/
#
- name: Install Bash Kernel 1/2
  pip:
    name: bash_kernel
    extra_args: --user
    state: latest
    executable: pip3

- name: Install Bash Kernel 2/2
  shell: python3 -m bash_kernel.install

#
# https://github.com/root-project/cling
# See 'Jupyter Install C++ Cling Kernel'
# check out:
# https://xeus-cling.readthedocs.io/en/latest/index.html
# https://github.com/jupyter-xeus/xeus-cling
# https://blog.jupyter.org/xeus-is-now-a-jupyter-subproject-c4ec5a1bf30b
#

- name: Copy bashrc config
  copy: src=10-bashrc-jupyter
        dest=/home/{{user}}/.bashrc.d/
