---
- name: Install deps
  become: true
  apt:
    name:
    - build-essential
    - libxml2-dev
    - libxslt-dev
    - python3-dev
    - python3-pip
    - python3-venv
    state: latest

- name: Upgrade pip3
  become: true
  pip:
    name: pip
    state: latest
    executable: pip3

- name: Install virtualenv
  pip:
    name: virtualenv
    extra_args: --user
    state: latest
    executable: pip3

- name: Install setuptools
  pip:
    name: setuptools
    extra_args: --user
    state: latest
    executable: pip3

- name: Copy scripts
  copy: src={{item}}
        dest=/home/{{user}}/.local/bin/{{item}}
        mode=0755
        backup=true
  with_items:
  - run-py3-script.sh

- name: Install youtube-dl
  pip:
    name: youtube-dl
    extra_args: --user
    state: latest
    executable: pip3

- name: Install yt-dlp
  pip:
    name: yt-dlp
    extra_args: --user
    state: latest
    executable: pip3

# https://streamlink.github.io/index.html
- name: Install streamlink
  pip:
    name: streamlink
    extra_args: --user
    state: latest
    executable: pip3

# GPlayCli is a command line tool to search, install,
# update Android applications from the Google Play Store.
- name: Install GPlayCli
  pip:
    name: gplaycli
    extra_args: --user
    state: latest
    executable: pip3

- name: Install pdf2txt 1/2
  pip:
    name: pdfminer.six
    extra_args: --user
    state: latest
    executable: pip3

- name: Simlink pdf2txt 2/2
  file:
    src: /home/{{user}}/.local/bin/run-py3-script.sh
    dest: /home/{{user}}/.local/bin/{{item}}
    state: link
  with_items:
  - pdf2txt
  - dumppdf
