---
- name: Install deps
  become: true
  apt:
    name:
    - build-essential
    - libxml2-dev
    - libxslt-dev
    - python3-dev
    - python3-pip
    state: latest

- name: Upgrade pip3
  become: true
  pip:
    name: pip
    state: latest
    executable: pip3

- name: Install youtube-dl
  pip:
    name: youtube-dl
    extra_args: --user
    state: latest
    executable: pip3
