---
- name: Remove repo's version
  become: true
  apt:
    name:
    - skype
    - skype-bin:i386
    state: absent
    purge: true

#
# https://snapcraft.io/skype
#

- name: Install 1/2
  become: true
  community.general.snap:
    name: skype
    classic: true

- name: Install 2/2
  copy: src=/snap/skype/current/meta/gui/skypeforlinux.desktop
        dest=/home/{{user}}/.local/share/applications/
