---
- name: Create sys dirs
  become: true
  file: path={{item.path}}
        mode={{item.mode}}
        state=directory
  with_items:
  - {path: /usr/local/bin, mode: 755}
  - {path: "{{cache_dir}}", mode: 777}

- name: Create user dirs
  file: path={{item.path}}
        mode={{item.mode}}
        state=directory
  with_items:
  - {path: "/home/{{user}}/.bashrc.d", mode: 755}
  - {path: "/home/{{user}}/.config/autostart", mode: 755}
  - {path: "/home/{{user}}/.config/xfce4/terminal", mode: 755}
  - {path: "/home/{{user}}/.local/bin", mode: 755}
  - {path: "/home/{{user}}/bin", mode: 755}
  - {path: "/home/{{user}}/tmp", mode: 755}
  - {path: "/home/{{user}}/projects", mode: 755}
  - {path: "/home/{{user}}/projects/tmp", mode: 755}

- name: Copy global configs
  become: true
  copy: src={{item.name}}
        dest={{item.path}}/{{item.name}}
        backup=true
  with_items:
  - {name: locale, path: /etc/default}

- name: Copy local configs
  copy: src={{item.name}}
        dest={{item.path}}/{{item.name}}
        backup=true
  with_items:
  - {name: .bashrc,                      path: "/home/{{user}}"}
  - {name: .Xmodmap,                     path: "/home/{{user}}"}
  - {name: terminalrc,                   path: "/home/{{user}}/.config/xfce4/terminal"}
  - {name: xfce4-keyboard-shortcuts.xml, path: "/home/{{user}}/.config/xfce4/xfconf/xfce-perchannel-xml"}
  - {name: xfce4-panel.xml,              path: "/home/{{user}}/.config/xfce4/xfconf/xfce-perchannel-xml"}

- name: Copy local scripts
  copy: src={{item}}
        dest=/home/{{user}}/bin/{{item}}
        mode=0755
        backup=true
  with_items:
  - capslock-to-control.sh
  - const
  - jekyll
  - man-examples
  - press-capslock.sh
  - stat-file
  - stat-fs
  - suggest
  - wineconst

- name: Copy autostart configs
  copy: src={{item}}
        dest=/home/{{user}}/.config/autostart/{{item}}
        backup=true
  with_items:
  - capslock-to-control.desktop

- name: Update apt's cache
  become: true
  # update cache once a day
  apt: update_cache=true cache_valid_time=86400

- name: Install apt-file
  become: true
  apt: name=apt-file state=latest

- name: Ensure apt-file cache dir
  become: true
  file: path=/var/cache/apt/apt-file/
        mode=755
        state=directory

- name: Register apt-file change time
  # local time (secs since Epoch) minus
  # the folder's last change time (secs since Epoch)
  shell: echo $((`date +%s`-`stat /var/cache/apt/apt-file/ -c%Z`))
  register: ctime
  changed_when: false

- name: Update apt-file's cache
  become: true
  # update once a month
  command: apt-file update
  when: ctime.stdout|int > 2592000

- name: Remove unneeded stuff
  become: true
  apt:
    name:
    - aisleriot
    - apache2
    - apache2-utils # ab, logrotate, etc
    - aptitude
    - banshee
    - celluloid # Video Player
    - cowsay
    - drawing
    - fortune
    - gnome-mahjongg
    - gnome-mines
    - gnome-sudoku
    - hypnotix # Free IPTV
    - mono-runtime
    - parole
    - pinta # Image editor
    - pix
    - rhythmbox
    - sgt-puzzles
    - thermald
    - tomboy
    - totem
    - vino     # VNC server
    - vinagre  # VNC client
    - warpinator # Local network file sharing
    - xplayer  # Mint's port of totem
    - xreader  # Mint's port of evince
    - xterm
    - xtightvncviewer
    state: absent

- name: Install common stuff
  become: true
  apt:
    name:
    - audacity # sound editing
    - ansible
    - apache2-utils # ab, rotatelogs
    - apt-transport-https
    - ascii
    - bless # hex editor
    - bmon # bandwidth monitor and rate estimator
    - build-essential
    - ca-certificates
    - cheese # Camera App, see also fswebcam
    - socat
    - curl
    - cutecom # GUI mini,pico com
    - dante-client # socksify
    - dia
    - dia-shapes
    - dnsutils # dig, nslookup
    - dos2unix
    - dumpasn1 # Dump/check ANS.1 binary
    - elinks   # ELinks is a text mode WWW browser
    - entr # inotify runner
    - evince
    - expect
    - expect-dev # autoexpect
    - ffmpeg
    - fping
    - fswebcam # Camera App, see also cheese
    - gimp
    - gimp-help-en
    - gnupg-agent
    - gnuplot
    - gnuplot-x11 # conflicts with gnuplot-nox
    - gparted
    - graphviz
    - graphviz-doc
    - gsfonts-x11 # dia recommends
    - hexdiff
    - htop
    - hypnotix # IPTV App
    - iftop # display bandwidth usage on an interface by host
    - inetutils-traceroute # traceroute
    - inotify-tools
    - kcachegrind
    - libnss3 # to fix "NSS >= 3.26 is required..." google-chome startup error
    - libxml2-utils # provides xmllint
    - mc
    - mediainfo
    - mediainfo-gui
    - mercurial
    - minicom
    - moreutils # for errno
    - mpg321 # for mpg123 :)
    - mscgen # http://www.mcternan.me.uk/mscgen/index.html
    - net-tools # ifconfig
    - ngrep # network grep
    - nload # network monitor
    - nmap
    - nmon
    - openvpn
    - pandoc # docx, pdf, markdown, etc converter
    - picocom # like minicom
    - pv # monitor the progress of data through a pipe
    - pwgen
    - qpdf # for zlib-flate
    - rar # see unrar
    - rdesktop # see also RDP server http://xrdp.org/ & https://www.freerdp.com/
    - rlwrap
    - sip-tester # SIPp
    - sipsak # SIP Swiss Army Knife
    - software-properties-common # add-apt-repository
    - spell
    - stoken
    - stress  # see also stress-ng
    #- sysbench # benchmark tool for database systems
    - sysstat # iostat
    - testdisk # deleted file recovery (photorec)
    - thunar # xfce4 file manager
    - timeshift
    - tree
    - tzdata # for DMU
    - unrar # see rar
    - uuid
    - vlc
    - vpnc
    - wget
    - whois
    - wireshark # TODO: sudo apt remove wireshark && sudo add-apt-repository ppa:wireshark-dev/stable -y && sudo apt update && sudo apt install wireshark # sudo apt install ssldump
    - wxhexeditor # hex editor
    - xclip
    - xdotool
    - xfce4-panel             # see also xfce4-panel.xml
    - xfce4-power-manager-plugins
    - xfce4-pulseaudio-plugin
    - xfce4-screenshooter
    - xfce4-weather-plugin    # see also xfce4-panel.xml
    state: latest

- name: Use correct time zone
  become: true
  file: src=/usr/share/zoneinfo/Europe/Minsk
        dest=/etc/localtime
        state=link
        force=true

- name: Install NTP
  become: true
  apt:
    name:
    - ntp
    - ntpdate
    state: latest

- name: Start NTP
  become: true
  service: name=ntp
           enabled=true
           state=started

- name: Install SSH
  become: true
  apt:
    name:
    - openssh-client
    - openssh-server
    - sshfs
    state: latest

- name: Start SSH
  become: true
  service: name=ssh
           enabled=true
           state=started
