---
- name: Create user dirs
  file: path={{item.path}}
        mode={{item.mode}}
        state=directory
  with_items:
  - {path: "/home/{{user}}/.gdb", mode: 755}

- name: Install
  become: true
  apt:
    name:
    - binutils
    - binutils-doc
    - cgdb # gdb console front-end
    - ddd  # gdb graphical front-end
    - gdb
#    - ltrace # build from source
    - latrace
    - pax-utils # dumpelf lddtree scanelf
    - strace # https://strace.io/
    - valgrind
    state: latest

- name: Copy bashrc config
  copy: src=01-bashrc-gdb
        dest=/home/{{user}}/.bashrc.d/
        backup=true

- name: Copy .gdbinit config
  copy: src=dot_gdbinit
        dest=/home/{{user}}/.gdbinit
        backup=true

- name: Copy gdb scripts
  copy: src=gdb/{{item}}
        dest=/home/{{user}}/.gdb/
        backup=true
  with_items:
  - env.py
