---
- name: Install
  become: true
  apt:
    name:
    - binutils
    - binutils-doc
    - ddd # debuggers front-end
    - gdb
#    - ltrace # build from source
    - latrace
    - pax-utils # dumpelf lddtree scanelf
    - strace # https://strace.io/
    - valgrind
    state: latest

- name: Copy bashrc config
  copy: src=01-bashrc-gdb
        dest=/home/{{user}}/.bashrc.d/
        backup=true

- name: Copy .gdbinit config
  copy: src=dot_gdbinit
        dest=/home/{{user}}/.gdbinit
        backup=true
