---
- name: Update /etc/security/limits.conf file
  become: true
  blockinfile:
    dest: /etc/security/limits.conf
    backup: yes
    insertafter: EOF
    block: |
      {{user}} soft nofile 10000
      {{user}} hard nofile 20000
    state: present

# Sets up user limits according to
# /etc/security/limits.conf. See above
- name: Update /etc/pam.d/su file
  become: true
  lineinfile: dest=/etc/pam.d/su
              regexp="^session    required   pam_limits.so"
              insertafter='^# session    required   pam_limits.so'
              line="session    required   pam_limits.so"
              state=present
