---
- set_fact:
    handlers:
    - {scheme: devhelpx, desktop: devhelpx.desktop, handler: devhelpx.sh}
    - {scheme: djvux   , desktop: djvux.desktop   , handler: evincex.sh}
    - {scheme: manx    , desktop: manx.desktop    , handler: manx.sh}
    - {scheme: openx   , desktop: openx.desktop   , handler: openx.sh}
    - {scheme: pdfx    , desktop: pdfx.desktop    , handler: evincex.sh}
    - {scheme: remsh   , desktop: remshx.desktop  , handler: remshx.sh}
    - {scheme: ssh     , desktop: sshx.desktop    , handler: sshx.sh}

- name: Copy files
  copy: src={{item}}
        dest=/home/{{user}}/bin/{{item}}
        mode=0755
  with_items:
  - utilx.sh

- name: Copy handlers
  copy: src={{item.handler}}
        dest=/home/{{user}}/bin/{{item.handler}}
        mode=0755
  with_items:
  - "{{handlers}}"

#
# ${XDG_DATA_HOME:-$HOME/.local/share}/applications/
#
- name: Copy desktops
  copy: src={{item.desktop}}
        dest=/home/{{user}}/.local/share/applications/{{item.desktop}}
        backup=true
  with_items:
  - "{{handlers}}"

#
# Adds 'x-scheme-handler/SCHEME=SCHEME.desktop' to
# ${XDG_CONFIG_HOME:-$HOME/.config}/mimeapps.list
# under '[Default Applications]'
# $ xdg-mime query default x-scheme-handler/pdfx
# pfdx.desktop
# $ xdg-open pdfx://PATH/TO/FILE.pdf
#
- name: Register MIME types
  command: xdg-mime default {{item.desktop}} {{item.scheme}}
  with_items:
  - "{{handlers}}"

- name: Update MIME database
  command: update-mime-database /home/{{user}}/.local/share/mime
