---
# https://launchpad.net/~plt/+archive/ubuntu/racket

- name: Add apt key
  become: true
  apt_key: keyserver=keyserver.ubuntu.com
           id=D9D33FCD84D82C17288BA03B3C9A6980F827E01E
           state=present

- name: Add apt repo
  become: true
  apt_repository: repo='deb http://ppa.launchpad.net/plt/racket/ubuntu trusty main'
                  state=present

- name: Install
  become: true
  apt: name={{item}}
       state=present
  with_items:
  - racket
  - racket-doc
